# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '4ae60bbf3d37d14f38a3055c493f313190c35addddaa6572814ef75a272e869e'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack