# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '315bb91f557386aa5bbf225babad4281048a8e3062884e82bffe7e68b18234b0'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack