# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:sandy rig_hash set value 'f71dcce6bbeb13bbc6f3a7555f7f47c7280e311efe1af764b8a1c2c0a0298fb8'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy