# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:haley rig_hash set value 'fd9bc8270cfc7043d802804a1336dc91142149e6c7e917b7e95714c5a11fac8f'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy