# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'a816ba1e5c0e983c5196783b2cf2818dea5bbcdd4aa81d463138fec4f62c9e6a'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack