# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'a4228277a284e91e74eeb49d900a2598be532397cd1deeeede9d961ef2d4de77'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack