# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:marnie rig_hash set value '4a44facf1b344402df1007e9340671f1aad8c5cf3477e9440fa274058043acdb'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy