# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:pam rig_hash set value '8d8809743ff57a3cc093c598630ad808ac36502a186457b46366eea205781e16'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy