# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'b3e025d6ff08de37c936fdccb0b7f8527037936f5e108922d7a66babc3092472'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack