# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:wizard rig_hash set value '7abb5f818ccd9c80f2f564e879b7af3b143fdbe2aa3694783ee93ce9a2186eea'
scoreboard objectives add aj.idle.frame dummy