# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:pig rig_hash set value '77e21582ffe936a8fda55f89e6d9e3ace2b2c5d104cade26e7ab93b161900f1f'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy