# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:sheep rig_hash set value '4ae60bbf3d37d14f38a3055c493f313190c35addddaa6572814ef75a272e869e'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy