# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:vincent rig_hash set value 'e1ea1502743427a64ffb74bc9d311505132626f34de90dcb99de60803e531b51'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy