# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:elliott rig_hash set value '817427d487ad8b8c9c6b5611fc9a5eeef27c33c7eaec64a633c84bc68727d3db'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy