# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0.0001f,1.498f,0f,0.0001f,-1f,0.0001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hair) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0071f,1.4996f,0f,-0.0071f,-1f,0.0001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0071f,1.498f,0f,-0.0071f,-1f,0.0001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arm_left) {transformation: [-0.9855f,-0.0736f,-0.1529f,0.3125f,-0.0743f,0.9972f,-0.0013f,1.4355f,0.1525f,0.0101f,-0.9882f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0.0011f,0.748f,0f,0.0011f,-1f,-0.0007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_left) {transformation: [-1f,0f,0f,0.125f,0f,1f,0.0003f,0.6872f,0f,0.0003f,-1f,0.0001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_right) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0.0003f,0.6872f,0f,0.0003f,-1f,0.0001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}