# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone) {transformation: [-1f,0f,0f,-0.25f,0f,0.9995f,0.0301f,1.4485f,0f,0.0301f,-0.9995f,0.0362f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hair) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0071f,1.45f,0f,-0.0071f,-1f,0.0362f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0071f,1.4485f,0f,-0.0071f,-1f,0.0362f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arm_left) {transformation: [-0.9578f,-0.0739f,-0.2778f,0.3125f,-0.0938f,0.9938f,0.0591f,1.3862f,0.2717f,0.0826f,-0.9588f,0.0316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9973f,0.0738f,0.7005f,0f,0.0738f,-0.9973f,-0.0191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_left) {transformation: [-1f,0f,0f,0.125f,0f,1f,0.0089f,0.6811f,0f,0.0089f,-1f,0.0032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_right) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0.0089f,0.6811f,0f,0.0089f,-1f,0.0032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}