# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0.0064f,1.4967f,0f,0.0064f,-1f,0.0222f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hair) {transformation: [-1f,0f,0f,0f,0f,0.998f,0.0632f,1.4983f,0f,0.0632f,-0.998f,0.0223f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.998f,0.0632f,1.4967f,0f,0.0632f,-0.998f,0.0222f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arm_left) {transformation: [-0.985f,-0.0694f,-0.1578f,0.3125f,-0.079f,0.9954f,0.0551f,1.4342f,0.1532f,0.0668f,-0.9859f,0.0202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9995f,0.0315f,0.7471f,0f,0.0315f,-0.9995f,-0.0014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_left) {transformation: [-1f,0f,0f,0.125f,0f,1f,0.0006f,0.6873f,0f,0.0006f,-1f,0.0001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_right) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0.0006f,0.6873f,0f,0.0006f,-1f,0.0001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}