# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0.0047f,1.4986f,0f,0.0047f,-1f,0.0172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hair) {transformation: [-1f,0f,0f,0f,0f,0.9986f,0.0523f,1.5001f,0f,0.0523f,-0.9986f,0.0173f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9986f,0.0523f,1.4986f,0f,0.0523f,-0.9986f,0.0172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arm_left) {transformation: [-0.9857f,-0.0702f,-0.1529f,0.3125f,-0.0777f,0.996f,0.0434f,1.4361f,0.1492f,0.0547f,-0.9873f,0.0157f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9997f,0.0238f,0.7488f,0f,0.0238f,-0.9997f,-0.0007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_left) {transformation: [-1f,0f,0f,0.125f,0f,1f,0.0003f,0.6875f,0f,0.0003f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_right) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0.0003f,0.6875f,0f,0.0003f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}