# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:lewis rig_hash set value '522d6ec3f11cc80c8a2f8997f28dad79b5063884d0ad8312ae568a22e1d0ab46'
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.idle.frame dummy