# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'fe6440a505e33d3ade0888241a802ffa0ac254ad296275d61d3d02879444cdf1'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack