# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.george.root] run return 0
execute if entity @s[tag=aj.george.animation.idle.playing] run function animated_java:george/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.george.animation.walk.playing] run function animated_java:george/animations/walk/zzz/on_tick
execute on passengers run rotate @s ~ ~