# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:gunther rig_hash set value 'e48a08f76e344cf72779834e6be239f2c4964a49aafef7747694124c49981dc4'
scoreboard objectives add aj.idle.frame dummy