# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '825fabca4722771250aafc98dda5f1f4830b6e24dca4d430ba0e931583f3bc74'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack