# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '8275609cbc1a15bbc840fc48144215630ae2a251fdfca82407518c6772aaa568'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack