# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:chicken rig_hash set value '00147baf9f88e98b232ea95c1feb68104a62ce4ccc4ac8e742613bc6233fa163'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy