# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:linus rig_hash set value 'a4228277a284e91e74eeb49d900a2598be532397cd1deeeede9d961ef2d4de77'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy