# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:sam rig_hash set value 'ce491fb54c310d23b8e0c59a4c25eca65a701a3bbfb04d72640d0d41f4e27752'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy