# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:rabbit rig_hash set value 'fe6440a505e33d3ade0888241a802ffa0ac254ad296275d61d3d02879444cdf1'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy