# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '42168d25d993dcec2000c40f0f6bfabfec4032c3e5bdd3a33647a46108b3f4ca'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack