# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:jas rig_hash set value '7154ca3cc1193269815184169d84260e8d87c8b8dfbe2ba9d4ae11cb94c802a0'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy