# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:chicken_baby rig_hash set value '10783bc04530686ecf959ac34506871e22b75150ce24909fcad1a12ccd15bedf'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy