# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_ear_left) {transformation: [-0.9973f,0.0738f,-0.0002f,0.0789f,0.0726f,0.9824f,0.1723f,0.3495f,0.0129f,0.1718f,-0.985f,0.309f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ear_right) {transformation: [-0.9957f,-0.0929f,-0.0002f,-0.0788f,-0.0916f,0.9808f,0.1723f,0.348f,-0.0158f,0.1716f,-0.985f,0.3088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,-0.0096f,-0.0002f,0f,-0.0095f,0.985f,0.1723f,0.3635f,-0.0015f,0.1723f,-0.985f,0.2321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,0f,0f,0.9999f,0.0106f,0.3494f,0f,0.0106f,-0.9999f,-0.2073f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9999f,0.0106f,0.2326f,0f,0.0106f,-0.9999f,0.0094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_left) {transformation: [-1f,0f,0f,0.1125f,0f,1f,0f,0.148f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_right) {transformation: [-1f,0f,0f,-0.1125f,0f,1f,0f,0.148f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_left) {transformation: [-1f,0f,0f,0.1125f,0f,1f,0f,0.1105f,0f,0f,-1f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_right) {transformation: [-1f,0f,0f,-0.1125f,0f,1f,0f,0.1105f,0f,0f,-1f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}