# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:caroline rig_hash set value '29c25107188d3b9eafd35dc9a3ac882d239d3f6decd01c09342203beea1d56a0'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy