# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_ear_left) {transformation: [-1f,0f,0f,0.1314f,0f,0.9681f,0.2504f,0.7937f,0f,0.2504f,-0.9681f,0.4329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ear_right) {transformation: [-1f,0f,0f,-0.1313f,0f,0.9681f,0.2504f,0.7937f,0f,0.2504f,-0.9681f,0.4329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9681f,0.2504f,0.6156f,0f,0.2504f,-0.9681f,0.3813f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5842f,0f,0f,-1f,-0.3506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3935f,0f,0f,-1f,0.0125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_left) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.2469f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_right) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,0.2469f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_left) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.2469f,0f,0f,-1f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_right) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,0.2469f,0f,0f,-1f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}