# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1185f,0f,0f,-1f,-0.1507f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftwing) {transformation: [-1f,0f,0f,0.0594f,0f,1f,0f,0.0766f,0f,0f,-1f,-0.2062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightwing) {transformation: [-1f,0f,0f,-0.0594f,0f,1f,0f,0.0766f,0f,0f,-1f,-0.2062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,0.0009f,0f,1f,0f,0.1133f,0f,0f,-1f,-0.269f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.0006f,0f,1f,0f,0.0875f,0f,0f,-1f,-0.1828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.0406f,0f,0.9984f,0.0567f,0.0266f,0f,0.0567f,-0.9984f,-0.2119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,-0.0406f,0f,1f,0f,0.0156f,0f,0f,-1f,-0.1869f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}