# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,-0.0087f,-0.0003f,0f,1f,0f,0.1133f,0.0087f,0f,-1f,-0.1507f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftwing) {transformation: [-1f,0f,0.0087f,0.0596f,0f,1f,0f,0.0714f,-0.0087f,0f,-1f,-0.2057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightwing) {transformation: [-1f,0f,0.0087f,-0.0592f,0f,1f,0f,0.0714f,-0.0087f,0f,-1f,-0.2068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0.0087f,0.0017f,0f,1f,0f,0.1081f,-0.0087f,0f,-1f,-0.2689f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0.0087f,0.0006f,0f,1f,0f,0.0823f,-0.0087f,0f,-1f,-0.1828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.0406f,0f,0.9999f,-0.0152f,0.0097f,0f,-0.0152f,-0.9999f,-0.1662f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,-0.0406f,0f,0.8678f,0.497f,0.035f,0f,0.497f,-0.8678f,-0.2347f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}