# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,-0.0044f,-0.0001f,0f,1f,0f,0.1153f,0.0044f,0f,-1f,-0.1507f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftwing) {transformation: [-1f,0f,0.0044f,0.0595f,0f,1f,0f,0.0734f,-0.0044f,0f,-1f,-0.206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightwing) {transformation: [-1f,0f,0.0044f,-0.0593f,0f,1f,0f,0.0734f,-0.0044f,0f,-1f,-0.2065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0.0044f,0.0013f,0f,1f,0f,0.1101f,-0.0044f,0f,-1f,-0.269f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0.0044f,0.0006f,0f,1f,0f,0.0844f,-0.0044f,0f,-1f,-0.1828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.0406f,0f,1f,0.0009f,0.0119f,0f,0.0009f,-1f,-0.1778f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,-0.0406f,0f,0.9487f,0.3162f,0.0311f,0f,0.3162f,-0.9487f,-0.2268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}