# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0.0044f,0.0001f,0f,1f,0f,0.1222f,-0.0044f,0f,-1f,-0.1507f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftwing) {transformation: [-1f,0f,-0.0044f,0.0593f,0f,1f,0f,0.0803f,0.0044f,0f,-1f,-0.2065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightwing) {transformation: [-1f,0f,-0.0044f,-0.0595f,0f,1f,0f,0.0803f,0.0044f,0f,-1f,-0.206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,-0.0044f,0.0006f,0f,1f,0f,0.117f,0.0044f,0f,-1f,-0.269f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,-0.0044f,0.0006f,0f,1f,0f,0.0912f,0.0044f,0f,-1f,-0.1828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.0406f,0f,0.9995f,0.0319f,0.0211f,0f,0.0319f,-0.9995f,-0.203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,-0.0406f,0f,0.9988f,-0.048f,0.0336f,0f,-0.048f,-0.9988f,-0.1943f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}