# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'fd9bc8270cfc7043d802804a1336dc91142149e6c7e917b7e95714c5a11fac8f'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack