# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'e48a08f76e344cf72779834e6be239f2c4964a49aafef7747694124c49981dc4'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack