# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '874fe0c6e87ad9b96778417449f4715db952d7a653976544cd6cd77df3640aab'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack