# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:abigail rig_hash set value '7b8d57fa684e300d2cc7ff330c92b1544aee8f70016df3b8a78e31ff7d4c4dd0'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy