# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'ce5a3b91d6d88546a82d3ee08d27ca8443642c9a4ff4ddf320e6c718d5da68e7'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack