package com.stardew.craft.communitycenter.reward.panning;

import com.stardew.craft.StardewCraft;
import com.stardew.craft.communitycenter.state.CCStoryFlags;
import com.stardew.craft.core.ModDimensions;
import com.stardew.craft.core.ModMiningDimensions;
import com.stardew.craft.network.payload.PanPointSyncPayload;
import net.minecraft.core.BlockPos;
import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.Tag;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.material.Fluids;
import net.minecraft.world.level.saveddata.SavedData;
import net.neoforged.neoforge.network.PacketDistributor;
import org.jetbrains.annotations.NotNull;

import javax.annotation.Nullable;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import java.util.UUID;

/**
 * Per-player, per-dimension ore-pan point state.
 * <p>
 * SDV parity (StardewValley/GameLocation.cs:13739 performOrePanTenMinuteUpdate
 * + Pan.cs:107 orePanPoint clearing):
 * <ul>
 *   <li>Each player owns at most one active {@code orePanPoint} per dimension.</li>
 *   <li>Points are generated by the 10-minute tick only when the player has
 *       the {@code ccFishTank} mail flag, mirroring SDV's
 *       {@code MasterPlayer.mailReceived.Contains("ccFishTank")} gate.</li>
 *   <li>When a point is panned (or cleared by the daily reset), it's removed
 *       and a fresh one may spawn on the next tick.</li>
 *   <li>{@code timesPanned} is a per-player lifetime counter used as part of
 *       the loot RNG seed, matching SDV {@code who.stats.Get("TimesPanned")}.</li>
 * </ul>
 * State is persisted on the overworld data-storage so it survives restarts,
 * independent of which dimension a player is in.
 */
public final class OrePanPointManager extends SavedData {

    private static final String DATA_NAME = "stardew_ore_pan_points";

    /** Per-(player × dimension) active point. */
    private final Map<UUID, Map<ResourceKey<Level>, BlockPos>> points = new HashMap<>();
    /** Per-player lifetime pan counter — used in loot RNG seed. */
    private final Map<UUID, Integer> timesPanned = new HashMap<>();

    // ──────────────── Accessors ────────────────

    @Nullable
    public BlockPos getPoint(UUID playerId, ServerLevel level) {
        Map<ResourceKey<Level>, BlockPos> byDim = points.get(playerId);
        return byDim == null ? null : byDim.get(level.dimension());
    }

    public void setPoint(UUID playerId, ServerLevel level, BlockPos pos) {
        points.computeIfAbsent(playerId, k -> new HashMap<>()).put(level.dimension(), pos);
        setDirty();
    }

    public void clearPoint(UUID playerId, ServerLevel level) {
        Map<ResourceKey<Level>, BlockPos> byDim = points.get(playerId);
        if (byDim != null && byDim.remove(level.dimension()) != null) {
            setDirty();
        }
    }

    public int getTimesPanned(UUID playerId) {
        return timesPanned.getOrDefault(playerId, 0);
    }

    public int incrementTimesPanned(UUID playerId) {
        int next = getTimesPanned(playerId) + 1;
        timesPanned.put(playerId, next);
        setDirty();
        return next;
    }

    // ──────────────── Generation (10-min tick) ────────────────

    /**
     * Called every in-game 10-minute boundary. For each online player with the
     * {@code ccFishTank} flag who does NOT have an active pan point in their
     * current dimension, attempt to place one near them.
     * <p>
     * SDV parity: GameLocation.performOrePanTenMinuteUpdate — 8 random tries,
     * {@code r.NextBool()} (50%) gate before the loop.
     */
    public static void performTenMinuteUpdate(MinecraftServer server) {
        // ── Perf early-exit 1: no players online ──
        var players = server.getPlayerList().getPlayers();
        if (players.isEmpty()) return;

        // ── Perf early-exit 2: iterate once and filter down to eligible players ──
        // Most players on a typical server won't have ccFishTank yet; skipping
        // them avoids all subsequent work (dim check, water scan, RNG).
        java.util.List<ServerPlayer> eligible = null;
        for (ServerPlayer player : players) {
            if (!(player.level() instanceof ServerLevel level)) continue;
            ResourceKey<Level> dim = level.dimension();
            if (!dim.equals(ModDimensions.STARDEW_VALLEY) && !dim.equals(ModMiningDimensions.STARDEW_MINING)) continue;
            if (!CCStoryFlags.hasFlag(player, CCStoryFlags.CC_FISH_TANK)) continue;
            if (eligible == null) eligible = new java.util.ArrayList<>(4);
            eligible.add(player);
        }
        if (eligible == null) return;

        // ── Only touch SavedData when there's at least one candidate ──
        OrePanPointManager mgr = get(server.overworld());
        Random r = new Random();

        for (ServerPlayer player : eligible) {
            ServerLevel level = (ServerLevel) player.level();
            if (mgr.getPoint(player.getUUID(), level) != null) continue;
            // SDV: r.NextBool() gate — 50% chance this tick
            if (!r.nextBoolean()) continue;

            BlockPos chosen = findWaterTileNear(level, player.blockPosition(), r);
            if (chosen != null) {
                mgr.setPoint(player.getUUID(), level, chosen);
                mgr.syncToClient(player);
                StardewCraft.LOGGER.debug(
                    "[PANNING] Generated ore-pan point at {} for {} in {}",
                    chosen, player.getName().getString(), level.dimension().location());
            }
        }
    }

    /**
     * SDV: 8 random tries to pick a water tile in the location. We sample in a
     * radius around the player for per-player relevance.
     */
    @Nullable
    private static BlockPos findWaterTileNear(ServerLevel level, BlockPos center, Random r) {
        // Radius large enough to find water in towns/rivers but close enough
        // that the glow stays visible to the player.
        final int radius = 24;
        // Worst-case block reads: 8 tries × 10 Y-scans × 2 reads = 160.
        // Typical case (water near player): first-try success in 1–3 reads.
        for (int tries = 0; tries < 8; tries++) {
            int dx = r.nextInt(radius * 2 + 1) - radius;
            int dz = r.nextInt(radius * 2 + 1) - radius;
            int probeY = center.getY() + 3;
            // Tight Y scan — 10 blocks from player+3 downward covers shorelines,
            // docks, and swimmers without trawling chunks far below the player.
            for (int dy = 0; dy < 10; dy++) {
                BlockPos p = new BlockPos(center.getX() + dx, probeY - dy, center.getZ() + dz);
                if (!level.getFluidState(p).is(Fluids.WATER)) continue;
                if (!level.getBlockState(p.above()).isAir()) continue;
                return p;
            }
        }
        return null;
    }

    // ──────────────── Sync ────────────────

    public void syncToClient(ServerPlayer player) {
        BlockPos pos = getPoint(player.getUUID(), (ServerLevel) player.level());
        PanPointSyncPayload payload = new PanPointSyncPayload(
            pos != null, pos != null ? pos : BlockPos.ZERO);
        PacketDistributor.sendToPlayer(player, payload);
    }

    /** Send a clear-all message (used on dimension change). */
    public static void syncEmpty(ServerPlayer player) {
        PacketDistributor.sendToPlayer(player, new PanPointSyncPayload(false, BlockPos.ZERO));
    }

    // ──────────────── SavedData boilerplate ────────────────

    public static OrePanPointManager get(ServerLevel level) {
        ServerLevel persistent = level.getServer().overworld();
        if (persistent == null) persistent = level;
        return persistent.getDataStorage().computeIfAbsent(
            new SavedData.Factory<>(OrePanPointManager::new, OrePanPointManager::load),
            DATA_NAME);
    }

    public static OrePanPointManager load(CompoundTag tag, HolderLookup.Provider provider) {
        OrePanPointManager mgr = new OrePanPointManager();

        ListTag playersList = tag.getList("Players", Tag.TAG_COMPOUND);
        for (int i = 0; i < playersList.size(); i++) {
            CompoundTag p = playersList.getCompound(i);
            UUID uuid = p.getUUID("UUID");
            int timesP = p.getInt("TimesPanned");
            if (timesP > 0) mgr.timesPanned.put(uuid, timesP);

            ListTag dimList = p.getList("Dims", Tag.TAG_COMPOUND);
            Map<ResourceKey<Level>, BlockPos> byDim = new HashMap<>();
            for (int j = 0; j < dimList.size(); j++) {
                CompoundTag d = dimList.getCompound(j);
                String dimId = d.getString("Dim");
                ResourceKey<Level> key = ResourceKey.create(net.minecraft.core.registries.Registries.DIMENSION,
                    ResourceLocation.parse(dimId));
                BlockPos pos = new BlockPos(d.getInt("X"), d.getInt("Y"), d.getInt("Z"));
                byDim.put(key, pos);
            }
            if (!byDim.isEmpty()) mgr.points.put(uuid, byDim);
        }
        return mgr;
    }

    @Override
    @SuppressWarnings("null")
    public @NotNull CompoundTag save(@NotNull CompoundTag tag, @NotNull HolderLookup.Provider provider) {
        ListTag playersList = new ListTag();
        java.util.Set<UUID> allPlayers = new java.util.HashSet<>();
        allPlayers.addAll(points.keySet());
        allPlayers.addAll(timesPanned.keySet());

        for (UUID uuid : allPlayers) {
            CompoundTag p = new CompoundTag();
            p.putUUID("UUID", uuid);
            p.putInt("TimesPanned", timesPanned.getOrDefault(uuid, 0));

            ListTag dimList = new ListTag();
            Map<ResourceKey<Level>, BlockPos> byDim = points.get(uuid);
            if (byDim != null) {
                for (Map.Entry<ResourceKey<Level>, BlockPos> e : byDim.entrySet()) {
                    CompoundTag d = new CompoundTag();
                    d.putString("Dim", e.getKey().location().toString());
                    d.putInt("X", e.getValue().getX());
                    d.putInt("Y", e.getValue().getY());
                    d.putInt("Z", e.getValue().getZ());
                    dimList.add(d);
                }
            }
            p.put("Dims", dimList);
            playersList.add(p);
        }
        tag.put("Players", playersList);
        return tag;
    }
}
