# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.emily.root] run return 0
execute if entity @s[tag=aj.emily.animation.idle.playing] run function animated_java:emily/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.emily.animation.walk.playing] run function animated_java:emily/animations/walk/zzz/on_tick
execute on passengers run rotate @s ~ ~