# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:robin rig_hash set value 'ce5a3b91d6d88546a82d3ee08d27ca8443642c9a4ff4ddf320e6c718d5da68e7'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy