# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.demetrius.animation.idle.playing
tag @s remove aj.demetrius.animation.walk.playing