# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:cow_baby rig_hash set value '874fe0c6e87ad9b96778417449f4715db952d7a653976544cd6cd77df3640aab'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy