# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'f71dcce6bbeb13bbc6f3a7555f7f47c7280e311efe1af764b8a1c2c0a0298fb8'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack