# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '4a44facf1b344402df1007e9340671f1aad8c5cf3477e9440fa274058043acdb'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack