# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'dc7a855e99d6b01692ce7a237ea16b9c86bbd56f4361c159619101a06d163487'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack