# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:clint rig_hash set value '0055d90b72a651bad357022cf2f17deb259c910f6474b572dc68bd89dae3aa6d'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy