# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:dwarf rig_hash set value '35e1fff7463a2e6e8466491e84709254520ad57ee43fa9352a2af34d44511afd'
scoreboard objectives add aj.idle.frame dummy