# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:rabbit_baby rig_hash set value 'dc7a855e99d6b01692ce7a237ea16b9c86bbd56f4361c159619101a06d163487'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy