# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,-0.0044f,-0.0008f,0f,1f,0f,0.2965f,0.0044f,0f,-1f,-0.0094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftwing) {transformation: [-1f,0f,0.0044f,0.1747f,0f,1f,0f,0.1777f,-0.0044f,0f,-1f,-0.1242f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightwing) {transformation: [-1f,0f,0.0044f,-0.1758f,0f,1f,0f,0.1777f,-0.0044f,0f,-1f,-0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0.0044f,0.0034f,0f,1f,0f,0.2262f,-0.0044f,0f,-1f,-0.4297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0.0044f,0.0006f,0f,1f,0f,0.0637f,-0.0044f,0f,-1f,-0.1828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,-0.0562f,0f,0.9487f,0.3162f,0.0654f,0f,0.3162f,-0.9487f,-0.2372f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.0563f,0f,1f,0.0009f,0.0463f,0f,0.0009f,-1f,-0.1539f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}