# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3f,0f,0f,-1f,-0.0094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftwing) {transformation: [-1f,0f,0f,0.175f,0f,1f,0f,0.1813f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightwing) {transformation: [-1f,0f,0f,-0.175f,0f,1f,0f,0.1813f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,0.0023f,0f,1f,0f,0.2297f,0f,0f,-1f,-0.4297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.0006f,0f,1f,0f,0.0672f,0f,0f,-1f,-0.1828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,-0.0562f,0f,0.9984f,0.0567f,0.0609f,0f,0.0567f,-0.9984f,-0.1744f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.0563f,0f,1f,0f,0.05f,0f,0f,-1f,-0.1806f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}