# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0.0044f,0.0008f,0f,1f,0f,0.3041f,-0.0044f,0f,-1f,-0.0094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftwing) {transformation: [-1f,0f,-0.0044f,0.1753f,0f,1f,0f,0.1853f,0.0044f,0f,-1f,-0.1258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightwing) {transformation: [-1f,0f,-0.0044f,-0.1742f,0f,1f,0f,0.1853f,0.0044f,0f,-1f,0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,-0.0044f,0.0013f,0f,1f,0f,0.2338f,0.0044f,0f,-1f,-0.4297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,-0.0044f,0.0006f,0f,1f,0f,0.0713f,0.0044f,0f,-1f,-0.1828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,-0.0562f,0f,0.9988f,-0.048f,0.068f,0f,-0.048f,-0.9988f,-0.1431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.0563f,0f,0.9995f,0.0319f,0.0554f,0f,0.0319f,-0.9995f,-0.2144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}