# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0.0087f,0.0015f,0f,1f,0f,0.3062f,-0.0087f,0f,-1f,-0.0094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftwing) {transformation: [-1f,0f,-0.0087f,0.1755f,0f,1f,0f,0.1875f,0.0087f,0f,-1f,-0.1265f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightwing) {transformation: [-1f,0f,-0.0087f,-0.1734f,0f,1f,0f,0.1875f,0.0087f,0f,-1f,0.0015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,-0.0087f,0.0002f,0f,1f,0f,0.2359f,0.0087f,0f,-1f,-0.4297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,-0.0087f,0.0006f,0f,1f,0f,0.0734f,0.0087f,0f,-1f,-0.1828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,-0.0562f,0f,0.9941f,-0.1089f,0.0728f,0f,-0.1089f,-0.9941f,-0.1209f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.0563f,0f,0.9974f,0.072f,0.0594f,0f,0.072f,-0.9974f,-0.245f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}