# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1107f,0f,0f,-1f,-0.1507f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftwing) {transformation: [-1f,0f,0f,0.0594f,0f,1f,0f,0.0687f,0f,0f,-1f,-0.2062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightwing) {transformation: [-1f,0f,0f,-0.0594f,0f,1f,0f,0.0687f,0f,0f,-1f,-0.2062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,0.0009f,0f,1f,0f,0.1055f,0f,0f,-1f,-0.269f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.0006f,0f,1f,0f,0.0797f,0f,0f,-1f,-0.1828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}