# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '7b8d57fa684e300d2cc7ff330c92b1544aee8f70016df3b8a78e31ff7d4c4dd0'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack