# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'e1ea1502743427a64ffb74bc9d311505132626f34de90dcb99de60803e531b51'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack