# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:alex rig_hash set value 'dc6f259ae049d999d53c2cfc4203f833de1b544999a2b1dc153ac468de162587'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy