# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:emily rig_hash set value 'b3e025d6ff08de37c936fdccb0b7f8527037936f5e108922d7a66babc3092472'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy