# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '0055d90b72a651bad357022cf2f17deb259c910f6474b572dc68bd89dae3aa6d'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack