# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:harvey rig_hash set value 'b8f65fc49f959b651274f980e1fdff63dd957d5ed06a876769317a922348220b'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy