# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:sheep_baby rig_hash set value '8275609cbc1a15bbc840fc48144215630ae2a251fdfca82407518c6772aaa568'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy