# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '2936265c2271ea2e75fbe2a87a00682bee0fc9ea992179da73b2fdd1b74c908d'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack