# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:cow rig_hash set value '2936265c2271ea2e75fbe2a87a00682bee0fc9ea992179da73b2fdd1b74c908d'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy