# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:sebastian rig_hash set value '315bb91f557386aa5bbf225babad4281048a8e3062884e82bffe7e68b18234b0'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy