# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'f81bceb16d788b404380afffd7b253b5f3d8691c1535b87276252abb67b2b894'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack