# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:maru rig_hash set value '688627282486fc208b5f07be567e98a03d83acaf664bf5cbb931342a5ea5864a'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy