# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.george.node.wheel_left] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_wheel_left set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.george.node.wheel_right] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_wheel_right set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.george.node.lunyi] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_lunyi set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.george.node.hair] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_hair set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.george.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.george.node.arm_right1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_arm_right1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.george.node.arm_right] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_arm_right set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.george.node.arm_left1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_arm_left1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.george.node.arm_left] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_arm_left set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.george.node.body] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_body set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.george.node.leg_right1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leg_right1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.george.node.leg_right] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leg_right set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.george.node.leg_left1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leg_left1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.george.node.leg_left] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leg_left set from storage animated_java:gu out