# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '29c25107188d3b9eafd35dc9a3ac882d239d3f6decd01c09342203beea1d56a0'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack