# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '10783bc04530686ecf959ac34506871e22b75150ce24909fcad1a12ccd15bedf'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack