# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:goat rig_hash set value '3a75543257fde44058e6703d712ecb0ca551e7f3f4bf246f19ca6be675e69b05'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy