# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'ce491fb54c310d23b8e0c59a4c25eca65a701a3bbfb04d72640d0d41f4e27752'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack