# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:chicken_baby/animations/pause_all
tag @s add aj.chicken_baby.animation.idle.playing
scoreboard players set @s aj.idle.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:chicken_baby/animations/idle/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only