# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '91b73039cdf72067006493b3b02c0f9edf5267710b717f41693ab8a7df3e757a'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack