# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:penny rig_hash set value '825fabca4722771250aafc98dda5f1f4830b6e24dca4d430ba0e931583f3bc74'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy