# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_ear_left) {transformation: [-1f,0f,0f,0.0622f,0f,1f,0f,0.3258f,0f,0f,-1f,0.1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ear_right) {transformation: [-1f,0f,0f,-0.0622f,0f,1f,0f,0.3258f,0f,0f,-1f,0.1f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.225f,0f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1059f,0f,0f,-1f,-0.1451f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1_right) {transformation: [-1f,0f,0f,-0.0937f,0f,1f,0f,0.0625f,0f,0f,-1f,-0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1_left) {transformation: [-1f,0f,0f,0.0937f,0f,1f,0f,0.0625f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_left) {transformation: [-1f,0f,0f,0.125f,0f,1f,0f,0.0875f,0f,0f,-1f,-0.15f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_right) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.0875f,0f,0f,-1f,-0.15f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}