# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '7abb5f818ccd9c80f2f564e879b7af3b143fdbe2aa3694783ee93ce9a2186eea'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack