# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '35e1fff7463a2e6e8466491e84709254520ad57ee43fa9352a2af34d44511afd'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack