# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.wizard.root] run return 0
execute if entity @s[tag=aj.wizard.animation.idle.playing] run function animated_java:wizard/animations/idle/zzz/on_tick
execute on passengers run rotate @s ~ ~