# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:pig_baby rig_hash set value 'a816ba1e5c0e983c5196783b2cf2818dea5bbcdd4aa81d463138fec4f62c9e6a'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy