# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:marlon rig_hash set value '433ffeac74b33e60a4032c33bdff8b39a8be802a7354c359131272ba0765704e'
scoreboard objectives add aj.idle.frame dummy