# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'b8f65fc49f959b651274f980e1fdff63dd957d5ed06a876769317a922348220b'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack