# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '8d8809743ff57a3cc093c598630ad808ac36502a186457b46366eea205781e16'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack