# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:jodi rig_hash set value '91b73039cdf72067006493b3b02c0f9edf5267710b717f41693ab8a7df3e757a'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy