# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_ear_left) {transformation: [-0.9999f,-0.0154f,0f,0.1314f,-0.0152f,0.9918f,0.1269f,0.6578f,-0.0019f,0.1269f,-0.9919f,0.4981f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ear_right) {transformation: [-0.9999f,0.0168f,0f,-0.1313f,0.0166f,0.9918f,0.1269f,0.658f,0.0021f,0.1269f,-0.9919f,0.4982f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0.0007f,0f,0f,0.0007f,0.9919f,0.1269f,0.6766f,0.0001f,0.1269f,-0.9919f,0.3691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0016f,0.6441f,0f,-0.0016f,-1f,-0.3628f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0016f,0.454f,0f,-0.0016f,-1f,0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_left) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.2499f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_right) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,0.2499f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_left) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.1874f,0f,0f,-1f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_right) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,0.1874f,0f,0f,-1f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}