# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:demetrius rig_hash set value '2320680f51c38c44b0a17d15e8b4c95615940dfb522fab6e586dfc8e4a16549a'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy