# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_ear_left) {transformation: [-0.9934f,-0.1145f,0f,0.1316f,-0.1142f,0.9906f,0.0747f,0.8075f,-0.0085f,0.0742f,-0.9972f,0.3633f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ear_right) {transformation: [-0.9932f,0.1162f,0f,-0.1313f,0.1158f,0.9905f,0.0747f,0.8077f,0.0087f,0.0742f,-0.9972f,0.3633f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0.0008f,0f,0f,0.0008f,0.9972f,0.0747f,0.6232f,0.0001f,0.0747f,-0.9972f,0.3441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-1f,0.0033f,-0.0023f,0f,0.0032f,0.9985f,0.0542f,0.204f,0.0025f,0.0542f,-0.9985f,-0.1136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0099f,0.5849f,0f,-0.0099f,-1f,-0.3563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0099f,0.3978f,0f,-0.0099f,-1f,0.0087f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_left) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.247f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_right) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,0.247f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_left) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.247f,0f,0f,-1f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_right) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,0.247f,0f,0f,-1f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}