param(
    [Parameter(Mandatory = $true)]
    [string]$SourceRegionDir,

    [switch]$CleanTarget
)

$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptDir

$targetRoot = Join-Path $repoRoot 'src\main\resources\pregen\stardew_valley'
$targetRegionDir = Join-Path $targetRoot 'region'
$manifestPath = Join-Path $targetRoot 'region_manifest.txt'

if (-not (Test-Path -Path $SourceRegionDir -PathType Container)) {
    throw "SourceRegionDir does not exist: $SourceRegionDir"
}

New-Item -ItemType Directory -Path $targetRegionDir -Force | Out-Null

if ($CleanTarget) {
    Get-ChildItem -Path $targetRegionDir -Filter '*.mca' -File -ErrorAction SilentlyContinue |
        Remove-Item -Force
}

$sourceFiles = Get-ChildItem -Path $SourceRegionDir -Filter '*.mca' -File |
    Sort-Object Name

if ($sourceFiles.Count -eq 0) {
    throw "No .mca files found in: $SourceRegionDir"
}

foreach ($file in $sourceFiles) {
    Copy-Item -Path $file.FullName -Destination (Join-Path $targetRegionDir $file.Name) -Force
}

$targetFiles = Get-ChildItem -Path $targetRegionDir -Filter '*.mca' -File |
    Sort-Object Name

$manifestLines = @(
    '# Auto-generated by scripts/setup_valley_pregen.ps1',
    '# One region filename per line'
)
$manifestLines += $targetFiles.Name

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllLines($manifestPath, $manifestLines, $utf8NoBom)

Write-Host "[VALLEY_PREGEN] Source: $SourceRegionDir"
Write-Host "[VALLEY_PREGEN] Copied: $($sourceFiles.Count) files"
Write-Host "[VALLEY_PREGEN] Target: $targetRegionDir"
Write-Host "[VALLEY_PREGEN] Manifest: $manifestPath"
