#!/usr/bin/env python3
"""Generate English translations for all missing keys in en_us.json."""
import json, re

with open('src/main/resources/assets/stardewcraft/lang/en_us.json') as f:
    en = json.load(f)
with open('src/main/resources/assets/stardewcraft/lang/zh_cn.json') as f:
    zh = json.load(f)

missing = sorted(set(zh.keys()) - set(en.keys()))

# === Item/block name overrides (key suffix -> English name) ===
NAME_FIX = {
    "autumns_bounty": "Autumn's Bounty",
    "autumn_s_bounty": "Autumn's Bounty",
    "dish_o_the_sea": "Dish O' The Sea",
    "miners_treat": "Miner's Treat",
    "miner_s_treat": "Miner's Treat",
    "farmers_lunch": "Farmer's Lunch",
    "farmer_s_lunch": "Farmer's Lunch",
    "oil_of_garlic": "Oil of Garlic",
    "jack_o_lantern": "Jack-O-Lantern",
    "qi_fruit": "Qi Fruit",
    "qi_bean": "Qi Bean",
    "qi_seasoning": "Qi Seasoning",
    "joja_cola": "Joja Cola",
    "l_goat_milk": "Large Goat Milk",
    "l_milk": "Large Milk",
    "l_egg": "Large Egg",
    "l_brown_egg": "Large Brown Egg",
    "cranberries": "Cranberries",
}

# === MANUAL translations for all non-programmatic keys ===
M = {
    # ── comments ──
    "_comment_tv": "========== TV System ==========",
    "_comment_tv_cooking_desc": "===== Cooking Descriptions (from Tv_CookingChannel) =====",
    "_comment_tv_tips": "===== Tip Channel (from Tv_TipChannel, keys = daysPlayed % 224) =====",

    # ── config.jade.plugin ──
    "config.jade.plugin_stardewcraft.animal_utility": "Animal Utility Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.bait_maker": "Bait Maker Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.bee_house": "Bee House Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.cask": "Cask Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.charcoal_kiln": "Charcoal Kiln Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.cheese_press": "Cheese Press Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.coop_animal": "Animal Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.crab_pot": "Crab Pot Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.crop_fertilizer": "Crop Fertilizer Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.crop_info": "Crop Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.crystalarium": "Crystalarium Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.dehydrator": "Dehydrator",
    "config.jade.plugin_stardewcraft.farmland_fertilizer": "Farmland Fertilizer Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.fish_smoker": "Fish Smoker Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.furnace": "Furnace Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.hay_hopper": "Hay Hopper Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.incubator": "Incubator Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.lightning_rod": "Lightning Rod Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.loom": "Loom Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.mayonnaise_machine": "Mayonnaise Machine Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.oil_maker": "Oil Maker Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.preserves_jar": "Preserves Jar",
    "config.jade.plugin_stardewcraft.seed_maker": "Seed Maker Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.solar_panel": "Solar Panel Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.tapper": "Tapper Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.tree_sapling_info": "Tree / Sapling Info (StardewCraft)",
    "config.jade.plugin_stardewcraft.worm_bin": "Worm Bin Info (StardewCraft)",

    # ── config.stardewcraft.barn_manager ──
    "config.stardewcraft.barn_manager.min_door_count": "Minimum Door/Fence-gate Count",
    "config.stardewcraft.barn_manager.require_door": "Require Door/Fence-gate on Border",
    "config.stardewcraft.barn_manager.scan_range_up": "Barn Scan Range (Up)",
    "config.stardewcraft.barn_manager.scan_range_xz": "Barn Scan Range (Horizontal)",
    "config.stardewcraft.barn_manager.tier1.autofeed_trough": "T1 Auto-feed Trough Required",
    "config.stardewcraft.barn_manager.tier1.feed_trough": "T1 Feed Trough Required",
    "config.stardewcraft.barn_manager.tier1.hay_hopper": "T1 Hay Hopper Required",
    "config.stardewcraft.barn_manager.tier1.incubator": "T1 Incubator Required",
    "config.stardewcraft.barn_manager.tier1.min_interior_blocks": "T1 Minimum Interior Blocks",
    "config.stardewcraft.barn_manager.tier2.feed_trough": "T2 Feed Trough Required",
    "config.stardewcraft.barn_manager.tier2.incubator": "T2 Incubator Required",
    "config.stardewcraft.barn_manager.tier2.min_interior_blocks": "T2 Minimum Interior Blocks",
    "config.stardewcraft.barn_manager.tier3.autofeed_trough": "T3 Auto-feed Trough Required",
    "config.stardewcraft.barn_manager.tier3.feed_trough": "T3 Feed Trough Required",
    "config.stardewcraft.barn_manager.tier3.hay_hopper": "T3 Hay Hopper Required",
    "config.stardewcraft.barn_manager.tier3.incubator": "T3 Incubator Required",
    "config.stardewcraft.barn_manager.tier3.min_interior_blocks": "T3 Minimum Interior Blocks",
    "config.stardewcraft.barn_manager.validation_hints": "Show Detailed Validation Hints",

    # ── config.stardewcraft.coop_manager ──
    "config.stardewcraft.coop_manager.min_door_count": "Minimum Door/Fence-gate Count",
    "config.stardewcraft.coop_manager.require_door": "Require Door/Fence-gate on Border",
    "config.stardewcraft.coop_manager.require_enclosed": "Require Coop Enclosed",
    "config.stardewcraft.coop_manager.scan_range_down": "Coop Scan Range (Down)",
    "config.stardewcraft.coop_manager.scan_range_up": "Coop Scan Range (Up)",
    "config.stardewcraft.coop_manager.scan_range_xz": "Coop Scan Range (Horizontal)",
    "config.stardewcraft.coop_manager.tier1.autofeed_trough": "T1 Auto-feed Trough Required",
    "config.stardewcraft.coop_manager.tier1.feed_trough": "T1 Feed Trough Required",
    "config.stardewcraft.coop_manager.tier1.hay_hopper": "T1 Hay Hopper Required",
    "config.stardewcraft.coop_manager.tier1.incubator": "T1 Incubator Required",
    "config.stardewcraft.coop_manager.tier1.min_interior_blocks": "T1 Minimum Interior Blocks",
    "config.stardewcraft.coop_manager.tier2.autofeed_trough": "T2 Auto-feed Trough Required",
    "config.stardewcraft.coop_manager.tier2.feed_trough": "T2 Feed Trough Required",
    "config.stardewcraft.coop_manager.tier2.hay_hopper": "T2 Hay Hopper Required",
    "config.stardewcraft.coop_manager.tier2.incubator": "T2 Incubator Required",
    "config.stardewcraft.coop_manager.tier2.min_interior_blocks": "T2 Minimum Interior Blocks",
    "config.stardewcraft.coop_manager.tier3.autofeed_trough": "T3 Auto-feed Trough Required",
    "config.stardewcraft.coop_manager.tier3.feed_trough": "T3 Feed Trough Required",
    "config.stardewcraft.coop_manager.tier3.hay_hopper": "T3 Hay Hopper Required",
    "config.stardewcraft.coop_manager.tier3.incubator": "T3 Incubator Required",
    "config.stardewcraft.coop_manager.tier3.min_interior_blocks": "T3 Minimum Interior Blocks",
    "config.stardewcraft.coop_manager.validation_hints": "Show Detailed Validation Hints",

    # ── gui.stardew_craft.barn_manager ──
    "gui.stardew_craft.barn_manager.build": "Build",
    "gui.stardew_craft.barn_manager.confirm_demolish": "Click again to demolish",
    "gui.stardew_craft.barn_manager.confirm_relocate": "Click again to relocate",
    "gui.stardew_craft.barn_manager.confirm_warning": "Danger: this will affect building and animal data",
    "gui.stardew_craft.barn_manager.cur_size": "Interior space: %s blocks (%s\u00d7%s\u00d7%s)",
    "gui.stardew_craft.barn_manager.demolish": "Demolish",
    "gui.stardew_craft.barn_manager.dialog.back": "Back",
    "gui.stardew_craft.barn_manager.dialog.confirm": "Confirm",
    "gui.stardew_craft.barn_manager.dialog.confirm_demolish": "Confirm Demolish",
    "gui.stardew_craft.barn_manager.dialog.confirm_relocate": "Confirm Relocate",
    "gui.stardew_craft.barn_manager.dialog.demolish.blocked_animals": "There are still %s animals. Cannot demolish.",
    "gui.stardew_craft.barn_manager.dialog.demolish.line1": "Demolishing will delete the building record.",
    "gui.stardew_craft.barn_manager.dialog.demolish.line2": "Bound animals will also be removed.",
    "gui.stardew_craft.barn_manager.dialog.demolish.line3": "This action cannot be undone.",
    "gui.stardew_craft.barn_manager.dialog.demolish.title": "Are you sure you want to demolish this barn?",
    "gui.stardew_craft.barn_manager.dialog.relocate.line1": "The manager will become a relocation item.",
    "gui.stardew_craft.barn_manager.dialog.relocate.line2": "Place it at the new location and meet building requirements.",
    "gui.stardew_craft.barn_manager.dialog.relocate.line3": "Auto-feeding is disabled during relocation; animals are treated as outdoors at night.",
    "gui.stardew_craft.barn_manager.dialog.relocate.title": "Are you sure you want to relocate this manager?",
    "gui.stardew_craft.barn_manager.enclosed_ok": "Enclosed",
    "gui.stardew_craft.barn_manager.max": "Max Level",
    "gui.stardew_craft.barn_manager.missing": "Requirements Not Met",
    "gui.stardew_craft.barn_manager.need.auto_feed_trough": "Auto-feed Trough x%s needed",
    "gui.stardew_craft.barn_manager.need.door": "Doors/Fence-gates insufficient (need %s, have %s)",
    "gui.stardew_craft.barn_manager.need.enclosed": "Barn not enclosed",
    "gui.stardew_craft.barn_manager.need.hay_hopper": "Hay Hopper x%s needed",
    "gui.stardew_craft.barn_manager.need.incubator": "Incubator x%s needed",
    "gui.stardew_craft.barn_manager.need.interior": "No usable interior space detected",
    "gui.stardew_craft.barn_manager.need.interior_blocks": "Interior space insufficient (need %s, have %s)",
    "gui.stardew_craft.barn_manager.ready": "Ready",
    "gui.stardew_craft.barn_manager.relocate": "Relocate",
    "gui.stardew_craft.barn_manager.req_facilities": "Required: Trough %s Auto %s Hopper %s Incubator %s",
    "gui.stardew_craft.barn_manager.req_size": "Required interior: %s blocks",
    "gui.stardew_craft.barn_manager.stage": "Current stage: %s",
    "gui.stardew_craft.barn_manager.stage.t1": "Tier 1",
    "gui.stardew_craft.barn_manager.stage.t2": "Tier 2",
    "gui.stardew_craft.barn_manager.stage.t3": "Tier 3",
    "gui.stardew_craft.barn_manager.stage.unformed": "Unformed",
    "gui.stardew_craft.barn_manager.target": "Target: Tier %s",
    "gui.stardew_craft.barn_manager.upgrade": "Upgrade",

    # ── gui.stardew_craft.coop_manager ──
    "gui.stardew_craft.coop_manager.build": "Build",
    "gui.stardew_craft.coop_manager.confirm_demolish": "Click again to demolish",
    "gui.stardew_craft.coop_manager.confirm_warning": "Danger: this will affect building and animal data",
    "gui.stardew_craft.coop_manager.cur_size": "Interior space: %s blocks (%s\u00d7%s\u00d7%s)",
    "gui.stardew_craft.coop_manager.demolish": "Demolish",
    "gui.stardew_craft.coop_manager.dialog.back": "Back",
    "gui.stardew_craft.coop_manager.dialog.confirm": "Confirm",
    "gui.stardew_craft.coop_manager.dialog.confirm_demolish": "Confirm Demolish",
    "gui.stardew_craft.coop_manager.dialog.confirm_relocate": "Confirm Relocate",
    "gui.stardew_craft.coop_manager.dialog.demolish.blocked_animals": "There are still %s animals. Cannot demolish.",
    "gui.stardew_craft.coop_manager.dialog.demolish.line1": "Demolishing will delete the building record.",
    "gui.stardew_craft.coop_manager.dialog.demolish.line2": "Bound animals will also be removed.",
    "gui.stardew_craft.coop_manager.dialog.demolish.line3": "This action cannot be undone.",
    "gui.stardew_craft.coop_manager.dialog.demolish.title": "Are you sure you want to demolish this coop?",
    "gui.stardew_craft.coop_manager.dialog.relocate.line1": "The manager will become a relocation item.",
    "gui.stardew_craft.coop_manager.dialog.relocate.line2": "Place it at the new location and meet building requirements.",
    "gui.stardew_craft.coop_manager.dialog.relocate.line3": "Auto-feeding is disabled during relocation; animals are treated as outdoors at night.",
    "gui.stardew_craft.coop_manager.dialog.relocate.title": "Are you sure you want to relocate this manager?",
    "gui.stardew_craft.coop_manager.max": "Max Level",
    "gui.stardew_craft.coop_manager.missing": "Requirements Not Met",
    "gui.stardew_craft.coop_manager.need.auto_feed_trough": "Auto-feed Trough x%s needed",
    "gui.stardew_craft.coop_manager.need.door": "Doors/Fence-gates insufficient (need %s, have %s)",
    "gui.stardew_craft.coop_manager.need.feed_trough": "Feed Trough x%s needed",
    "gui.stardew_craft.coop_manager.need.hay_hopper": "Hay Hopper x%s needed",
    "gui.stardew_craft.coop_manager.need.incubator": "Incubator x%s needed",
    "gui.stardew_craft.coop_manager.need.interior": "No usable interior space detected",
    "gui.stardew_craft.coop_manager.need.interior_blocks": "Interior space insufficient (need %s, have %s)",
    "gui.stardew_craft.coop_manager.need.unknown": "Some requirements not met, please check structure",
    "gui.stardew_craft.coop_manager.ready": "Ready",
    "gui.stardew_craft.coop_manager.relocate": "Relocate",
    "gui.stardew_craft.coop_manager.req_facilities": "Required: Trough %s Auto %s Hopper %s Incubator %s",
    "gui.stardew_craft.coop_manager.req_size": "Required interior: %s blocks",
    "gui.stardew_craft.coop_manager.stage": "Current stage: %s",
    "gui.stardew_craft.coop_manager.stage.t1": "Tier 1",
    "gui.stardew_craft.coop_manager.stage.t2": "Tier 2",
    "gui.stardew_craft.coop_manager.stage.t3": "Tier 3",
    "gui.stardew_craft.coop_manager.stage.unformed": "Unformed",
    "gui.stardew_craft.coop_manager.target": "Target: Tier %s",
    "gui.stardew_craft.coop_manager.upgrade": "Upgrade",

    # ── gui.stardew_craft.elevator / mine_exit ──
    "gui.stardew_craft.elevator.current_floor": "Current floor: %s",
    "gui.stardew_craft.mine_exit.cancel": "Close",
    "gui.stardew_craft.mine_exit.current_floor": "Current floor: %s",
    "gui.stardew_craft.mine_exit.go_to_0": "Return to floor 0",
    "gui.stardew_craft.mine_exit.go_up": "Go up one floor",

    # ── itemGroup ──
    "itemGroup.stardewcraft.stardew": "StardewCraft",

    # ── key ──
    "key.categories.stardewcraft": "Stardew Valley",
    "key.stardewcraft.emote_wheel": "Emote Wheel",
    "key.stardewcraft.game_menu": "Game Menu",
    "key.stardewcraft.grow_crops": "Grow Crops (Debug)",
    "key.stardewcraft.skill_major": "Major Skill",
    "key.stardewcraft.skill_minor": "Minor Skill",

    # ── message ──
    "message.stardew_craft.ladder_found": "You found a ladder going down!",
    "message.stardew_craft.manager.break_blocked": "The building has not been demolished; the manager cannot be broken directly.",
    "message.stardew_craft.manager.demolish_has_animals": "This building still has animals (%s). Please transfer or remove them first.",
    "message.stardew_craft.manager.demolished": "Building demolished. Bound animals removed: %s.",
    "message.stardew_craft.manager.no_building": "No bound building found.",
    "message.stardew_craft.manager.relocate_owner_mismatch": "This relocation manager does not belong to you.",
    "message.stardew_craft.manager.relocate_pending": "Building is now inactive: auto-feeding disabled, animals treated as outdoors at night.",
    "message.stardew_craft.manager.relocate_pickup": "Manager picked up. Place it at the new location to reactivate.",
    "message.stardewcraft.cannot_break_elevator": "The elevator cannot be broken!",

    # ── recipe unlock conditions ──
    "recipe.stardewcraft.algae_soup.unlock_condition": "Reach 3 hearts with Clint",
    "recipe.stardewcraft.artichoke_dip.unlock_condition": "TV: Queen of Sauce (Year 1, Fall 28)",
    "recipe.stardewcraft.autumn_s_bounty.unlock_condition": "Reach 7 hearts with Demetrius",
    "recipe.stardewcraft.autumns_bounty.unlock_condition": "Reach 7 hearts with Demetrius",
    "recipe.stardewcraft.baked_fish.unlock_condition": "TV: Queen of Sauce (Year 1, Summer 7)",
    "recipe.stardewcraft.banana_pudding.unlock_condition": "Purchase with Ginger Island coins",
    "recipe.stardewcraft.bean_hotpot.unlock_condition": "Reach 7 hearts with Clint",
    "recipe.stardewcraft.blackberry_cobbler.unlock_condition": "TV: Queen of Sauce (Year 2, Fall 14)",
    "recipe.stardewcraft.blackberry_tart.unlock_condition": "TV: Queen of Sauce (Year 2, Fall 21)",
    "recipe.stardewcraft.blueberry_tart.unlock_condition": "Reach 3 hearts with Pierre",
    "recipe.stardewcraft.bread.unlock_condition": "TV: Queen of Sauce (Year 1, Summer 28) or Stardrop Saloon",
    "recipe.stardewcraft.bruschetta.unlock_condition": "TV: Queen of Sauce (Year 2, Winter 21)",
    "recipe.stardewcraft.carp_surprise.unlock_condition": "TV: Queen of Sauce (Year 2, Summer 7)",
    "recipe.stardewcraft.cheese_cauliflower.unlock_condition": "Reach 3 hearts with Pam",
    "recipe.stardewcraft.chocolate_cake.unlock_condition": "TV: Queen of Sauce (Year 1, Winter 14)",
    "recipe.stardewcraft.chowder.unlock_condition": "Reach 3 hearts with Willy",
    "recipe.stardewcraft.coleslaw.unlock_condition": "TV: Queen of Sauce (Year 1, Spring 14)",
    "recipe.stardewcraft.complete_breakfast.unlock_condition": "TV: Queen of Sauce (Year 2, Spring 21)",
    "recipe.stardewcraft.cookie.unlock_condition": "Evelyn 4-heart event",
    "recipe.stardewcraft.crab_cakes.unlock_condition": "TV: Queen of Sauce (Year 2, Fall 21)",
    "recipe.stardewcraft.cranberry_candy.unlock_condition": "TV: Queen of Sauce (Year 1, Winter 28)",
    "recipe.stardewcraft.cranberry_sauce.unlock_condition": "Reach 7 hearts with Clint",
    "recipe.stardewcraft.crispy_bass.unlock_condition": "Reach 3 hearts with Kent",
    "recipe.stardewcraft.dish_o_the_sea.unlock_condition": "Reach Mining Level 3",
    "recipe.stardewcraft.eggplant_parmesan.unlock_condition": "Reach 7 hearts with Lewis",
    "recipe.stardewcraft.escargot.unlock_condition": "Reach 5 hearts with Willy",
    "recipe.stardewcraft.farmer_s_lunch.unlock_condition": "Reach Farming Level 3",
    "recipe.stardewcraft.fiddlehead_risotto.unlock_condition": "TV: Queen of Sauce (Year 2, Fall 28)",
    "recipe.stardewcraft.fish_stew.unlock_condition": "Reach 7 hearts with Willy",
    "recipe.stardewcraft.fish_taco.unlock_condition": "Reach 7 hearts with Linus",
    "recipe.stardewcraft.fried_calamari.unlock_condition": "Reach 3 hearts with Jodi",
    "recipe.stardewcraft.fried_eel.unlock_condition": "Reach 3 hearts with George",
    "recipe.stardewcraft.fried_egg.unlock_condition": "Upgrade farmhouse",
    "recipe.stardewcraft.fried_mushroom.unlock_condition": "Reach 3 hearts with Demetrius",
    "recipe.stardewcraft.fruit_salad.unlock_condition": "TV: Queen of Sauce (Year 2, Fall 7)",
    "recipe.stardewcraft.ginger_ale.unlock_condition": "Purchase from Dwarf Shop",
    "recipe.stardewcraft.glazed_yams.unlock_condition": "TV: Queen of Sauce (Year 1, Fall 21)",
    "recipe.stardewcraft.hashbrowns.unlock_condition": "TV: Queen of Sauce (Year 2, Spring 14) or Stardrop Saloon",
    "recipe.stardewcraft.ice_cream.unlock_condition": "Reach 7 hearts with Jodi",
    "recipe.stardewcraft.lobster_bisque.unlock_condition": "TV: Queen of Sauce (Year 2, Winter 14) or reach 9 hearts with Willy",
    "recipe.stardewcraft.lucky_lunch.unlock_condition": "TV: Queen of Sauce (Year 2, Spring 28)",
    "recipe.stardewcraft.maki_roll.unlock_condition": "TV: Queen of Sauce (Year 1, Summer 21) or Stardrop Saloon",
    "recipe.stardewcraft.mango_sticky_rice.unlock_condition": "Reach 7 hearts with Leo",
    "recipe.stardewcraft.maple_bar.unlock_condition": "TV: Queen of Sauce (Year 2, Summer 14)",
    "recipe.stardewcraft.miner_s_treat.unlock_condition": "Reach Mining Level 3",
    "recipe.stardewcraft.miner_treat.unlock_condition": "Reach Mining Level 3",
    "recipe.stardewcraft.moss_soup.unlock_condition": "Reach Foraging Level 3",
    "recipe.stardewcraft.omelet.unlock_condition": "TV: Queen of Sauce (Year 1, Spring 28)",
    "recipe.stardewcraft.pale_broth.unlock_condition": "Reach 3 hearts with Marnie",
    "recipe.stardewcraft.pancakes.unlock_condition": "TV: Queen of Sauce (Year 1, Summer 14) or Stardrop Saloon",
    "recipe.stardewcraft.parsnip_soup.unlock_condition": "Reach 3 hearts with Caroline",
    "recipe.stardewcraft.pepper_poppers.unlock_condition": "Reach 3 hearts with Shane",
    "recipe.stardewcraft.pink_cake.unlock_condition": "TV: Queen of Sauce (Year 2, Summer 21)",
    "recipe.stardewcraft.pizza.unlock_condition": "TV: Queen of Sauce (Year 2, Spring 7) or Stardrop Saloon",
    "recipe.stardewcraft.plum_pudding.unlock_condition": "TV: Queen of Sauce (Year 1, Winter 7)",
    "recipe.stardewcraft.poi.unlock_condition": "Reach 3 hearts with Leo",
    "recipe.stardewcraft.poppyseed_muffin.unlock_condition": "TV: Queen of Sauce (Year 2, Winter 7)",
    "recipe.stardewcraft.pumpkin_pie.unlock_condition": "TV: Queen of Sauce (Year 1, Winter 21)",
    "recipe.stardewcraft.pumpkin_soup.unlock_condition": "Reach 7 hearts with Robin",
    "recipe.stardewcraft.radish_salad.unlock_condition": "TV: Queen of Sauce (Year 1, Spring 21)",
    "recipe.stardewcraft.red_plate.unlock_condition": "Reach 7 hearts with Emily",
    "recipe.stardewcraft.rhubarb_pie.unlock_condition": "Reach 7 hearts with Marnie",
    "recipe.stardewcraft.rice_pudding.unlock_condition": "Reach 7 hearts with Evelyn",
    "recipe.stardewcraft.roasted_hazelnuts.unlock_condition": "TV: Queen of Sauce (Year 2, Summer 28)",
    "recipe.stardewcraft.roots_platter.unlock_condition": "Reach Combat Level 3",
    "recipe.stardewcraft.salad.unlock_condition": "Reach 3 hearts with Emily",
    "recipe.stardewcraft.salmon_dinner.unlock_condition": "Reach 3 hearts with Gus",
    "recipe.stardewcraft.sashimi.unlock_condition": "Reach 3 hearts with Linus",
    "recipe.stardewcraft.seafoam_pudding.unlock_condition": "Reach Fishing Level 9",
    "recipe.stardewcraft.shrimp_cocktail.unlock_condition": "TV: Queen of Sauce (Year 2, Winter 28)",
    "recipe.stardewcraft.spaghetti.unlock_condition": "Reach 3 hearts with Lewis",
    "recipe.stardewcraft.spicy_eel.unlock_condition": "Reach 7 hearts with George",
    "recipe.stardewcraft.squid_ink_ravioli.unlock_condition": "Reach Combat Level 9",
    "recipe.stardewcraft.stir_fry.unlock_condition": "TV: Queen of Sauce (Year 1, Spring 7)",
    "recipe.stardewcraft.strange_bun.unlock_condition": "Reach 7 hearts with Shane",
    "recipe.stardewcraft.stuffing.unlock_condition": "Reach 7 hearts with Pam",
    "recipe.stardewcraft.super_meal.unlock_condition": "Reach 7 hearts with Kent",
    "recipe.stardewcraft.survival_burger.unlock_condition": "Reach Foraging Level 2",
    "recipe.stardewcraft.tom_kha_soup.unlock_condition": "Reach 7 hearts with Sandy",
    "recipe.stardewcraft.tortilla.unlock_condition": "TV: Queen of Sauce (Year 1, Fall 7) or Stardrop Saloon",
    "recipe.stardewcraft.triple_shot_espresso.unlock_condition": "Purchase from Stardrop Saloon",
    "recipe.stardewcraft.tropical_curry.unlock_condition": "Purchase from Ginger Island Resort",
    "recipe.stardewcraft.trout_soup.unlock_condition": "TV: Queen of Sauce (Year 1, Fall 14)",
    "recipe.stardewcraft.vegetable_medley.unlock_condition": "Reach 7 hearts with Caroline",

    # ── stardewcraft.animal ──
    "stardewcraft.animal.interact.already_pet": "Already petted today.",
    "stardewcraft.animal.interact.golden_cracker_already_used": "This animal has already eaten a Golden Animal Cracker.",
    "stardewcraft.animal.interact.golden_cracker_not_supported": "This animal cannot benefit from a Golden Animal Cracker.",
    "stardewcraft.animal.interact.info": "Animal: %s | Stage: %s | Growth: %s/%s",
    "stardewcraft.animal.interact.inspect_requires_pet": "Right-click to pet first, then Shift+Right-click to view info.",
    "stardewcraft.animal.interact.pet_success": "You gently petted it.",
    "stardewcraft.animal.produce.inventory_full": "Inventory full, please make some room.",
    "stardewcraft.animal.purchase.animals": "Animals",
    "stardewcraft.animal.purchase.buildings": "Buildings",
    "stardewcraft.animal.purchase.confirm": "Purchase",
    "stardewcraft.animal.purchase.failed": "Purchase failed.",
    "stardewcraft.animal.purchase.money": "Gold: %s",
    "stardewcraft.animal.purchase.name_duplicate": "Another animal already has that name.",
    "stardewcraft.animal.purchase.name_hint": "Name (supports Unicode)",
    "stardewcraft.animal.purchase.no_building": "No matching building.",
    "stardewcraft.animal.purchase.no_money": "Not enough gold.",
    "stardewcraft.animal.purchase.success": "Purchased: %s (cost %s).",
    "stardewcraft.animal.query.age_weeks": "Age: %s weeks",
    "stardewcraft.animal.query.age_weeks_baby": "Age: %s weeks (baby)",
    "stardewcraft.animal.query.age_years": "Age: %s",
    "stardewcraft.animal.query.confirm_sell": "Sell this animal?",
    "stardewcraft.animal.query.growth": "Growth: %s/%s days",
    "stardewcraft.animal.query.hover.move": "Move",
    "stardewcraft.animal.query.hover.repro": "Allow Pregnancy",
    "stardewcraft.animal.query.hover.sell": "Sell (%s)",
    "stardewcraft.animal.query.mood.1": "It looks very happy today.",
    "stardewcraft.animal.query.mood.2": "It seems okay, but could use more care.",
    "stardewcraft.animal.query.mood.3": "It seems a bit unhappy today.",
    "stardewcraft.animal.query.mood.4": "It looks hungry.",
    "stardewcraft.animal.query.mood.5": "It seems affected by the rain.",
    "stardewcraft.animal.query.mood.6": "It was left outside last night.",
    "stardewcraft.animal.query.mood.happy": "It looks very happy today.",
    "stardewcraft.animal.query.mood.neutral": "It seems okay, but could use more care.",
    "stardewcraft.animal.query.move_confirm": "Move here",
    "stardewcraft.animal.query.move_empty": "No available buildings.",
    "stardewcraft.animal.query.move_failed": "Animal relocation failed.",
    "stardewcraft.animal.query.move_status.available": "Available",
    "stardewcraft.animal.query.move_status.current": "Current",
    "stardewcraft.animal.query.move_status.full": "Full",
    "stardewcraft.animal.query.move_success": "Animal relocated successfully.",
    "stardewcraft.animal.query.move_unavailable": "Relocation is not yet available.",
    "stardewcraft.animal.query.pet_status.done": "Petted today: Done",
    "stardewcraft.animal.query.rename_duplicate": "Another animal already has that name.",
    "stardewcraft.animal.query.rename_hint": "Name",
    "stardewcraft.animal.query.stage": "Stage: %s",
    "stardewcraft.animal.query.stage.adult": "Adult",
    "stardewcraft.animal.query.stage.baby": "Baby",
    "stardewcraft.animal.shop.desc.cow": "Basic barn animal. Produces milk daily.",
    "stardewcraft.animal.shop.desc.duck": "Requires a bigger coop. Produces duck eggs.",
    "stardewcraft.animal.shop.desc.goat": "Requires a higher-tier barn. Produces goat milk.",
    "stardewcraft.animal.shop.desc.pig": "Requires a top-tier barn. Finds truffles outdoors.",
    "stardewcraft.animal.shop.desc.rabbit": "Rare and soft. Produces wool and rabbit's foot.",
    "stardewcraft.animal.shop.desc.sheep": "Requires a top-tier barn. Produces wool.",
    "stardewcraft.animal.shop.desc.white_chicken": "Classic coop animal. Produces eggs steadily.",
    "stardewcraft.animal.shop.lock.barn_t1": "Requires at least a Tier 1 Barn.",
    "stardewcraft.animal.shop.lock.barn_t2": "Requires at least a Tier 2 Barn.",
    "stardewcraft.animal.shop.lock.barn_t3": "Requires at least a Tier 3 Barn.",
    "stardewcraft.animal.shop.lock.coop_t1": "Requires at least a Tier 1 Coop.",
    "stardewcraft.animal.shop.lock.coop_t2": "Requires at least a Tier 2 Coop.",
    "stardewcraft.animal.shop.lock.coop_t3": "Requires at least a Tier 3 Coop.",
    "stardewcraft.animal.shop.pick_animal": "Choose an animal. Locked animals appear as silhouettes.",
    "stardewcraft.animal.shop.pick_home_name": "Select a building and name your new animal.",
    "stardewcraft.animal.shop.require_tier": "Required building tier: %s",

    # ── stardewcraft.command ──
    "stardewcraft.command.energy.added": "\u00a7bRestored %.1f energy (current: %.1f)",
    "stardewcraft.command.energy.consumed": "\u00a7bConsumed %.1f energy (current: %.1f)",
    "stardewcraft.command.energy.consumed_exhausted": "\u00a7bConsumed %.1f energy (current: %.1f)\u00a77 Exhausted!",
    "stardewcraft.command.energy.cured": "\u00a7aExhaustion cleared!",
    "stardewcraft.command.energy.info": "\u00a7bEnergy: %.1f/%d",
    "stardewcraft.command.energy.info_exhausted": "\u00a7bEnergy: %.1f/%d \u00a77(Exhausted)",
    "stardewcraft.command.exp.added": "\u00a7aAdded %d %s XP (current XP: %d)",
    "stardewcraft.command.exp.levelup": "\u00a7aCongratulations! %s leveled up to \u00a76Level %d\u00a7a!",
    "stardewcraft.command.exp.removed": "\u00a7cRemoved %d %s XP (current XP: %d, level: %d)",
    "stardewcraft.command.exp.set": "\u00a7eSet %s XP to: %d (level: %d)",
    "stardewcraft.command.health.info": "\u00a7cHealth: %d/%d",
    "stardewcraft.command.health.set": "\u00a7cSet health to: %d",
    "stardewcraft.command.health.setmax": "\u00a7cSet max health to: %d",
    "stardewcraft.command.lucky.info": "\u00a7dToday's luck: %.3f \u00a77(Year %d Season %d Day %d)",
    "stardewcraft.command.lucky.out_of_range": "\u00a7cOut of range! Available range: %.2f ~ %.2f",
    "stardewcraft.command.lucky.range": "\u00a77Available range: %.2f ~ %.2f",
    "stardewcraft.command.lucky.set": "\u00a7dSet today's luck to: %.3f \u00a77(Year %d Season %d Day %d)",
    "stardewcraft.command.money.added": "\u00a7eAdded %d gold (current: %d)",
    "stardewcraft.command.money.info": "\u00a7eGold: %d",
    "stardewcraft.command.money.insufficient": "\u00a7cNot enough gold!",
    "stardewcraft.command.money.removed": "\u00a7eRemoved %d gold (current: %d)",
    "stardewcraft.command.money.set": "\u00a7eSet gold to: %d",
    "stardewcraft.command.player.reset": "\u00a7ePlayer data has been reset!",
    "stardewcraft.command.profession.detail": "  \u00a7f%s",
    "stardewcraft.command.profession.header": "\u00a7dProfessions:",
    "stardewcraft.command.skill.detail": "  \u00a7f%s: \u00a7aLv %d \u00a77(XP: %d/%d, %.1f%%%)",
    "stardewcraft.command.skill.header": "\u00a7aSkill Levels:",

    # ── stardewcraft.configuration ──
    "stardewcraft.configuration.items": "Item List",
    "stardewcraft.configuration.logDirtBlock": "Log Dirt Block",
    "stardewcraft.configuration.magicNumber": "Magic Number",
    "stardewcraft.configuration.magicNumberIntroduction": "Magic Number Text",
    "stardewcraft.configuration.section.stardewcraft.common.toml": "StardewCraft Config",
    "stardewcraft.configuration.section.stardewcraft.common.toml.title": "StardewCraft Config",
    "stardewcraft.configuration.title": "StardewCraft Config",

    # ── stardewcraft.cooking ──
    "stardewcraft.cooking.buff.apply_when": "Applies: immediately upon eating",
    "stardewcraft.cooking.buff.duration": "Duration: %s",
    "stardewcraft.cooking.energy": "Energy %s",
    "stardewcraft.cooking.ingredient.any_fish": "Any Fish",
    "stardewcraft.cooking.ingredient.any_milk": "Any Milk",
    "stardewcraft.cooking.invalid_recipe": "Invalid recipe!",
    "stardewcraft.cooking.missing_ingredient": "Insufficient ingredient: %s x%d",
    "stardewcraft.cooking.no_oil": "Not enough oil (need %s)",
    "stardewcraft.cooking.page": "Page %s/%s",
    "stardewcraft.cooking.shift_hint": "Shift + Cook = Make 5",
    "stardewcraft.cooking.title": "Cooking",

    # ── stardewcraft.crafting ──
    "stardewcraft.crafting.invalid_recipe": "Invalid crafting recipe!",
    "stardewcraft.crafting.missing_ingredient": "Not enough materials to craft!",
    "stardewcraft.crafting.recipe_locked": "This crafting recipe has not been unlocked!",

    # ── stardewcraft.deco ──
    "stardewcraft.deco.screen.cancel": "Cancel",
    "stardewcraft.deco.screen.ok": "OK",
    "stardewcraft.deco.screen.title": "Decoration Selection",
    "stardewcraft.deco.unlock_hint.flooring_casino": "Source: Casino reward shop.",
    "stardewcraft.deco.unlock_hint.flooring_default": "Source: Pierre's rotating stock, Traveling Cart random stock, and various catalogue furniture.",
    "stardewcraft.deco.unlock_hint.flooring_junimo_catalogue": "Source: Junimo Catalogue furniture.",
    "stardewcraft.deco.unlock_hint.flooring_junimo_wizard_catalogue": "Source: Junimo Catalogue or Wizard Catalogue furniture.",
    "stardewcraft.deco.unlock_hint.flooring_retro_catalogue": "Source: Retro Catalogue furniture.",
    "stardewcraft.deco.unlock_hint.flooring_wizard_catalogue": "Source: Wizard Catalogue furniture.",
    "stardewcraft.deco.unlock_hint.wallpaper_casino": "Source: Casino reward shop.",
    "stardewcraft.deco.unlock_hint.wallpaper_catalogue_only": "Source: Catalogue special stock.",
    "stardewcraft.deco.unlock_hint.wallpaper_default": "Source: Pierre's rotating stock, Traveling Cart random stock, and various catalogue furniture.",
    "stardewcraft.deco.unlock_hint.wallpaper_desert_festival": "Source: Desert Festival special stall.",
    "stardewcraft.deco.unlock_hint.wallpaper_joja_shop": "Source: Joja Shop stock / Joja Catalogue furniture.",
    "stardewcraft.deco.unlock_hint.wallpaper_junimo_catalogue": "Source: Junimo Catalogue furniture.",
    "stardewcraft.deco.unlock_hint.wallpaper_retro_catalogue": "Source: Retro Catalogue furniture.",
    "stardewcraft.deco.unlock_hint.wallpaper_trash_catalogue": "Source: Trash Catalogue furniture.",
    "stardewcraft.deco.unlock_hint.wallpaper_winter_festival": "Source: Winter Festival shop rotation.",
    "stardewcraft.deco.unlock_hint.wallpaper_wizard_catalogue": "Source: Wizard Catalogue furniture.",

    # ── stardewcraft.emote ──
    "stardewcraft.emote.angry": "Angry",
    "stardewcraft.emote.blush": "Blush",
    "stardewcraft.emote.chat": "%s sent emote %s",
    "stardewcraft.emote.game": "Game",
    "stardewcraft.emote.happy": "Happy",
    "stardewcraft.emote.heart": "Heart",
    "stardewcraft.emote.note": "Note",
    "stardewcraft.emote.pause": "Pause",
    "stardewcraft.emote.question": "Question",
    "stardewcraft.emote.sad": "Sad",
    "stardewcraft.emote.sleep": "Sleep",
    "stardewcraft.emote.x": "X",

    # ── stardewcraft.fishing ──
    "stardewcraft.fishing.already_fishing": "You are already fishing.",
    "stardewcraft.fishing.bite": "A fish is biting! Right-click again to reel in",
    "stardewcraft.fishing.caught": "Caught: %s",
    "stardewcraft.fishing.hooked": "Hooked!",
    "stardewcraft.fishing.minigame.hint": "Hold Space/Right-click/Left-click to raise the bobber",
    "stardewcraft.fishing.minigame.perfect": "Perfect!",
    "stardewcraft.fishing.minigame.time": "Time remaining: %ss",
    "stardewcraft.fishing.minigame.title": "Fishing",
    "stardewcraft.fishing.not_aiming_water": "Please aim at water before casting.",
    "stardewcraft.fishing.not_water": "This is not water; cannot cast here.",

    # ── stardewcraft.game_menu.crafting ──
    "stardewcraft.game_menu.crafting.button_five_hint": "Craft 5 (Shift: max)",
    "stardewcraft.game_menu.crafting.button_one_hint": "Craft 1 (Shift: max)",
    "stardewcraft.game_menu.crafting.craft_five": "Craft x5",
    "stardewcraft.game_menu.crafting.craft_one": "Craft x1",
    "stardewcraft.game_menu.crafting.crafted_count": "Times crafted: %s",
    "stardewcraft.game_menu.crafting.empty": "No crafting recipes to display.",
    "stardewcraft.game_menu.crafting.hint": "Left-click recipe to craft. Shift for batch, Ctrl+Shift for bulk",
    "stardewcraft.game_menu.crafting.hint_click_recipe": "Click the same recipe again to craft: LMB x1, Shift x5, Ctrl+Shift x25, RMB x1",
    "stardewcraft.game_menu.crafting.ingredients": "Ingredients",
    "stardewcraft.game_menu.crafting.inventory_title": "Inventory",
    "stardewcraft.game_menu.crafting.max_craftable": "Can craft: %s",
    "stardewcraft.game_menu.crafting.no_ingredients": "No recognizable ingredients for this recipe.",
    "stardewcraft.game_menu.crafting.status_locked": "Locked",
    "stardewcraft.game_menu.crafting.status_unlocked": "Unlocked",
    "stardewcraft.game_menu.crafting.title": "Crafting",
    "stardewcraft.game_menu.crafting.unknown": "???",

    # ── stardewcraft.game_menu.social ──
    "stardewcraft.game_menu.social.empty": "No villager friendship data to display.",
    "stardewcraft.game_menu.social.hint": "Scroll or arrow keys to browse",
    "stardewcraft.game_menu.social.max": "Max Hearts",
    "stardewcraft.game_menu.social.page": "Position: %s / %s",
    "stardewcraft.game_menu.social.points": "%s points",
    "stardewcraft.game_menu.social.talked_no": "No",
    "stardewcraft.game_menu.social.talked_yes": "Yes",
    "stardewcraft.game_menu.social.title": "Social - Friendship",
    "stardewcraft.game_menu.social.to_next": "To next heart: %s",

    # ── stardewcraft.honey ──
    "stardewcraft.honey.flavored": "%1$s Honey",

    # ── stardewcraft.hud ──
    "stardewcraft.hud.date_format": "%s, Day %d",
    "stardewcraft.hud.fall": "Fall",
    "stardewcraft.hud.fish_catch": "Fish Catch Ready!",
    "stardewcraft.hud.friday": "Fri",
    "stardewcraft.hud.hay_collected": "Collected %s hay.",
    "stardewcraft.hud.hay_silo_full": "Silo full; hay dropped on the ground.",
    "stardewcraft.hud.requires_item": "Requires %s %s.",
    "stardewcraft.hud.saturday": "Sat",
    "stardewcraft.hud.skill_level_up": "%s Level Up",
    "stardewcraft.hud.spring": "Spring",
    "stardewcraft.hud.summer": "Summer",
    "stardewcraft.hud.sunday": "Sun",
    "stardewcraft.hud.thursday": "Thu",
    "stardewcraft.hud.tuesday": "Tue",
    "stardewcraft.hud.wednesday": "Wed",
    "stardewcraft.hud.winter": "Winter",
    "stardewcraft.hud.monday": "Mon",

    # ── stardewcraft.incubator ──
    "stardewcraft.incubator.claim.building_full": "Coop is full, please make room first.",
    "stardewcraft.incubator.claim.failed": "Hatch claim failed, please try again later.",
    "stardewcraft.incubator.claim.invalid_building": "Incubator is not inside a valid coop.",
    "stardewcraft.incubator.claim.invalid_egg": "This egg cannot be hatched here.",
    "stardewcraft.incubator.claim.not_owner": "You can only claim your own coop's incubator.",
    "stardewcraft.incubator.claim.not_ready": "Incubation is not yet complete.",
    "stardewcraft.incubator.claim.success": "Hatched successfully! A new animal has joined the coop.",

    # ── stardewcraft.jade ──
    "stardewcraft.jade.fertilizer": "Fertilizer: %s",
    "stardewcraft.jade.fertilizer.none": "None",
    "stardewcraft.jei.fishing_level": "Fishing Level",

    # ── stardewcraft.message ──
    "stardewcraft.message.holy_blade_dodge": "You dodged the damage!",
    "stardewcraft.message.seed.wrong_season": "It's not the right season to plant this crop.",
    "stardewcraft.message.tool.empty": "The watering can is empty.",
    "stardewcraft.message.tree.chop_stump": "Chop the stump at the bottom!",

    # ── stardewcraft.preserve ──
    "stardewcraft.preserve.aged_roe.flavored_name": "Aged %s Roe",
    "stardewcraft.preserve.dried_fruit.flavored_name": "Dried %s",
    "stardewcraft.preserve.dried_mushrooms.flavored_name": "Dried %s",
    "stardewcraft.preserve.jelly.flavored_name": "%s Jelly",
    "stardewcraft.preserve.pickles.flavored_name": "Pickled %s",
    "stardewcraft.preserve.roe.flavored_name": "%s Roe",
    "stardewcraft.preserve.smoked_fish.flavored_name": "Smoked %s",

    # ── stardewcraft.quality ──
    "stardewcraft.quality.gold": "Gold",
    "stardewcraft.quality.iridium": "Iridium",
    "stardewcraft.quality.normal": "Normal",
    "stardewcraft.quality.silver": "Silver",

    # ── stardewcraft.skill ──
    "stardewcraft.skill.combat": "Combat",
    "stardewcraft.skill.farming": "Farming",
    "stardewcraft.skill.fishing": "Fishing",
    "stardewcraft.skill.foraging": "Foraging",
    "stardewcraft.skill.mining": "Mining",

    # ── stardewcraft.sleep ──
    "stardewcraft.sleep.confirm.message": "End-of-day processing will begin immediately. Enter the next morning?",
    "stardewcraft.sleep.confirm.no": "No",
    "stardewcraft.sleep.confirm.title": "Ready to sleep for the night?",
    "stardewcraft.sleep.confirm.yes": "Yes",

    # ── stardewcraft.stone_chest / wooden_chest ──
    "stardewcraft.stone_chest.color_picker": "Chest Color",
    "stardewcraft.wooden_chest.color_picker": "Chest Color",

    # ── stardewcraft.tool ──
    "stardewcraft.tool.autofeed_trough_upgrader": "Tool",
    "stardewcraft.tool.axe": "Tool",
    "stardewcraft.tool.fishing_rod": "Tool",
    "stardewcraft.tool.hoe": "Tool",
    "stardewcraft.tool.pickaxe": "Mining Tool",
    "stardewcraft.tool.scythe": "Tool",
    "stardewcraft.tool.watering_can": "Tool",

    # ── stardewcraft.treasure ──
    "stardewcraft.treasure.close_hint": "Click or press ESC to take items",
    "stardewcraft.treasure.golden": "Golden Chest",
    "stardewcraft.treasure.golden.title": "\u00a76\u00a7lGolden Chest",
    "stardewcraft.treasure.normal": "Chest",
    "stardewcraft.treasure.title": "Chest",

    # ── stardewcraft.type ──
    "stardewcraft.type.animal_product": "Animal Product",
    "stardewcraft.type.artifact": "Artifact",
    "stardewcraft.type.artifact_quality": "Artifact (Quality)",
    "stardewcraft.type.artisan_animal_quality": "Artisan Product",
    "stardewcraft.type.artisan_goods": "Artisan Goods",
    "stardewcraft.type.carpet": "Carpet",
    "stardewcraft.type.cooking": "Food",
    "stardewcraft.type.cooking_ingredient": "Cooking Ingredient",
    "stardewcraft.type.crabpot": "Crab Pot Fish",
    "stardewcraft.type.craftable": "Craftable",
    "stardewcraft.type.crop": "Crop",
    "stardewcraft.type.crop_seed": "Crop Seed",
    "stardewcraft.type.fertilizer": "Fertilizer",
    "stardewcraft.type.fish": "Fish",
    "stardewcraft.type.fishing": "Fishing",
    "stardewcraft.type.forage": "Forage",
    "stardewcraft.type.fruit": "Fruit",
    "stardewcraft.type.furniture": "Furniture",
    "stardewcraft.type.legendary_fish": "Legendary Fish",
    "stardewcraft.type.mineral": "Mineral",
    "stardewcraft.type.misc": "Miscellaneous",
    "stardewcraft.type.resource": "Resource",
    "stardewcraft.type.seed": "Seed",
    "stardewcraft.type.tool": "Tool",
    "stardewcraft.type.trash": "Trash",
    "stardewcraft.type.utility": "Utility",
    "stardewcraft.type.weapon": "Weapon",
    "stardewcraft.type.weapon.dagger": "Dagger",
    "stardewcraft.type.weapon.slingshot": "Slingshot",
    "stardewcraft.type.weapon.sword": "Sword",

    # ── stardewcraft.ui.building ──
    "stardewcraft.ui.building.available": "Available",
    "stardewcraft.ui.building.count": "%d Buildings",
    "stardewcraft.ui.building.current": "Current",
    "stardewcraft.ui.building.full": "Full",
    "stardewcraft.ui.building.move_hint": "Click a building on the right to relocate instantly",
    "stardewcraft.ui.building.move_title": "Animal Relocation",
    "stardewcraft.ui.cooking.unlock_method": "Unlock method: %s",
    "stardewcraft.ui.cooking_pot.title": "Cooking Stove",
    "stardewcraft.ui.deco.currently_equipped": "Currently Equipped",

    # ── stardewcraft.weapon lore ──
    "stardewcraft.weapon.meowmere.lore": "\"It glows, it meows... and it hits surprisingly hard!\"",
    "stardewcraft.weapon.pirate_sword.lore": "Fortune favors the bold... and the outlaws.",
    "stardewcraft.weapon.rusty_sword.lore": "\"A rusty old sword, but in the darkness of the mines, it's still your most reliable companion.\"",
    "stardewcraft.weapon.skill.passive": "[Passive]",

    # ── weapon skill names ──
    "stardewcraft.weapon.skill.bone_fracture": "Bone Fracture",
    "stardewcraft.weapon.skill.bone_fracture.desc.1": "Effect: Horizontal slash applies Bone Fracture",
    "stardewcraft.weapon.skill.bone_fracture.desc.2": "Bone Fracture: Reduces attack and movement speed",
    "stardewcraft.weapon.skill.bone_fracture.effect.1": "Attack: -10% (4s)",
    "stardewcraft.weapon.skill.bone_fracture.effect.2": "Move Speed: -20% (4s)",

    "stardewcraft.weapon.skill.burglar_shank": "Burglar's Shank",
    "stardewcraft.weapon.skill.burglar_shank.desc.1": "Effect: Slash a single enemy in front",
    "stardewcraft.weapon.skill.burglar_shank.desc.2": "No kill: Applies Vulnerability II for 3s",
    "stardewcraft.weapon.skill.burglar_shank.effect.1": "Damage: 150%",
    "stardewcraft.weapon.skill.burglar_shank.effect.2": "Kill: +10G (Stardew dimension only)",
    "stardewcraft.weapon.skill.burglar_shank.effect.3": "Vulnerability II: 3s, crit rate +5%/level",

    "stardewcraft.weapon.skill.carving_thrust": "Carving Thrust",
    "stardewcraft.weapon.skill.carving_thrust.desc.1": "Effect: Triple thrust at nearest target within 2.5 blocks",
    "stardewcraft.weapon.skill.carving_thrust.desc.2": "Lock-on: Prioritizes single target",
    "stardewcraft.weapon.skill.carving_thrust.effect.1": "Multi-stab: 45% x3",
    "stardewcraft.weapon.skill.carving_thrust.effect.2": "Damage Reduction: 20% (0.25s)",
    "stardewcraft.weapon.skill.carving_thrust.effect.3": "Crit: Bonus 60% follow-up thrust",

    "stardewcraft.weapon.skill.claymore_foldback": "Claymore Foldback",
    "stardewcraft.weapon.skill.claymore_foldback.desc.1": "Effect: Two-stage slash (light \u2192 heavy)",
    "stardewcraft.weapon.skill.claymore_foldback.desc.2": "Both stages can stack hits",
    "stardewcraft.weapon.skill.claymore_foldback.effect.1": "Damage: 70% + 120%; return slash applies Imbalance (attack speed -20%, 2s)",

    "stardewcraft.weapon.skill.crescent_slash": "Crescent Slash",
    "stardewcraft.weapon.skill.crescent_slash.desc.1": "Effect: Wide arc slash in a forward cone",
    "stardewcraft.weapon.skill.crescent_slash.desc.2": "Hitting any target counts as success",
    "stardewcraft.weapon.skill.crescent_slash.effect.1": "No target: Still slashes and enters cooldown",

    "stardewcraft.weapon.skill.crystal_dagger_layer": "Crystal Layer",
    "stardewcraft.weapon.skill.crystal_dagger_layer.desc.1": "Effect: Thrust and gain 1 Crystal Layer",
    "stardewcraft.weapon.skill.crystal_dagger_layer.desc.2": "Full stacks: Next attack deals bonus damage",
    "stardewcraft.weapon.skill.crystal_dagger_layer.effect.1": "Crystal Layer: Crit rate +2%/stack (6s, max 4 stacks)",
    "stardewcraft.weapon.skill.crystal_dagger_layer.effect.2": "Full stacks: Next hit deals 80% bonus damage",

    "stardewcraft.weapon.skill.dark_sword_blood_debt": "Blood Debt",
    "stardewcraft.weapon.skill.dark_sword_blood_debt.desc.1": "Effect: Consume 6% current HP to unleash blood blade",
    "stardewcraft.weapon.skill.dark_sword_blood_debt.desc.2": "Next 5s: 20% of damage dealt returned as healing",
    "stardewcraft.weapon.skill.dark_sword_blood_debt.effect.1": "Duration: 5s",
    "stardewcraft.weapon.skill.dark_sword_blood_debt.effect.2": "Cost: 6% current HP",

    "stardewcraft.weapon.skill.dark_sword_blood_moon": "Blood Moon Harvest",
    "stardewcraft.weapon.skill.dark_sword_blood_moon.desc.1": "Effect: Enter Blood Moon for 4s, attack +35%",
    "stardewcraft.weapon.skill.dark_sword_blood_moon.desc.2": "Burns 1% max HP every 0.5s with lifesteal",
    "stardewcraft.weapon.skill.dark_sword_blood_moon.effect.1": "Energy: 10",
    "stardewcraft.weapon.skill.dark_sword_blood_moon.effect.2": "HP Burn: 1% max HP / 0.5s",
    "stardewcraft.weapon.skill.dark_sword_blood_moon.effect.3": "Finisher: 100% net HP burned as dark damage burst",

    "stardewcraft.weapon.skill.desperate_plunder": "Desperate Plunder",
    "stardewcraft.weapon.skill.desperate_plunder.desc.1": "Effect: A frenzied slash that costs your own HP",
    "stardewcraft.weapon.skill.desperate_plunder.desc.2": "Kill: Heal; No kill: Gain Rage",
    "stardewcraft.weapon.skill.desperate_plunder.effect.1": "Cost: 2 HP (1 heart)",
    "stardewcraft.weapon.skill.desperate_plunder.effect.2": "Kill: Restore 4 HP",
    "stardewcraft.weapon.skill.desperate_plunder.effect.3": "No kill: Rage +10% damage (3s)",

    "stardewcraft.weapon.skill.dragon_breath_judgement": "Dragon Breath Judgement",
    "stardewcraft.weapon.skill.dragon_breath_judgement.desc.1": "Condition: Requires \u226515 Dragon Breath, consumes all",
    "stardewcraft.weapon.skill.dragon_breath_judgement.desc.2": "Bonus: Each stack above 15 grants +4% crit rate",
    "stardewcraft.weapon.skill.dragon_breath_judgement.desc.3": "Passive: Normal attacks accumulate Dragon Breath and increase normal attack damage",
    "stardewcraft.weapon.skill.dragon_breath_judgement.desc.5": "Cap: 20 stacks",
    "stardewcraft.weapon.skill.dragon_breath_judgement.desc.6": "Bonus: +1% normal attack damage per stack",
    "stardewcraft.weapon.skill.dragon_breath_judgement.effect.1": "Range: 120\u00b0 cone / 4 block radius",
    "stardewcraft.weapon.skill.dragon_breath_judgement.effect.2": "Refund: Hits refund Dragon Breath, max 5 stacks",

    "stardewcraft.weapon.skill.dragon_breath_thrust": "Dragon Breath Thrust",
    "stardewcraft.weapon.skill.dragon_breath_thrust.effect.1": "Crit: +10% this strike",
    "stardewcraft.weapon.skill.dragon_breath_thrust.effect.2": "Vulnerability II: 4s (+20% damage taken)",
    "stardewcraft.weapon.skill.dragon_breath_thrust.effect.3": "Stagger: 2s",

    "stardewcraft.weapon.skill.dragontooth_shiv_breath": "Dragon Breath Mode",
    "stardewcraft.weapon.skill.dragontooth_shiv_breath.desc.1": "Effect: Enter Dragon Breath Mode for 6s, attacks count as backstab damage",
    "stardewcraft.weapon.skill.dragontooth_shiv_breath.desc.2": "Passive: Backstabs always crit",
    "stardewcraft.weapon.skill.dragontooth_shiv_stab": "Dragontooth Stab",
    "stardewcraft.weapon.skill.dragontooth_shiv_stab.effect.1": "Damage: 120%",
    "stardewcraft.weapon.skill.dragontooth_shiv_stab.effect.2": "No AI: 2s",

    "stardewcraft.weapon.skill.dwarf_dagger_rush": "Ley Line Rush",
    "stardewcraft.weapon.skill.dwarf_dagger_rush.desc.1": "Effect: Enter Ley Line Rush for 5s and gain Speed I",
    "stardewcraft.weapon.skill.dwarf_dagger_rush.desc.2": "During rush, thrust hits refresh thrust cooldown",
    "stardewcraft.weapon.skill.dwarf_dagger_rush.effect.1": "Speed I: 5s",
    "stardewcraft.weapon.skill.dwarf_dagger_rush.effect.2": "Thrust Refresh: On hit",
    "stardewcraft.weapon.skill.dwarf_dagger_rush.effect.3": "Cooldown: 15s",

    "stardewcraft.weapon.skill.dwarf_dagger_thrust": "Rune Thrust",
    "stardewcraft.weapon.skill.dwarf_dagger_thrust.desc.1": "Effect: Thrust forward up to 8 blocks",
    "stardewcraft.weapon.skill.dwarf_dagger_thrust.desc.2": "Hit: Restore energy and apply Vulnerability IV",
    "stardewcraft.weapon.skill.dwarf_dagger_thrust.effect.1": "Energy: +2 on hit",
    "stardewcraft.weapon.skill.dwarf_dagger_thrust.effect.2": "Vulnerability IV: 5s",
    "stardewcraft.weapon.skill.dwarf_dagger_thrust.effect.3": "Resistance III: 2.5s",

    "stardewcraft.weapon.skill.dwarf_fortress": "Ley Fortress: Aftershock",
    "stardewcraft.weapon.skill.dwarf_fortress.desc.1": "Effect: Slam ground and enter Fortress Mode for 4s",
    "stardewcraft.weapon.skill.dwarf_fortress.desc.2": "Taking damage triggers Ley Shockwave (max 4 times)",
    "stardewcraft.weapon.skill.dwarf_fortress.effect.1": "Energy: 10",
    "stardewcraft.weapon.skill.dwarf_fortress.effect.2": "Protection II + No knockback",
    "stardewcraft.weapon.skill.dwarf_fortress.effect.3": "Shockwave: 3 block radius, 100% damage",
    "stardewcraft.weapon.skill.dwarf_fortress.effect.4": "Echo: At 4 triggers, 4 block radius, 120% damage",

    "stardewcraft.weapon.skill.dwarf_rune_guard": "Rune Guard Slash",
    "stardewcraft.weapon.skill.dwarf_rune_guard.desc.1": "Effect: Activate Rune Guard and unleash an energy-restoring slash",
    "stardewcraft.weapon.skill.dwarf_rune_guard.desc.2": "Hit: Restore energy and apply Slow",
    "stardewcraft.weapon.skill.dwarf_rune_guard.effect.1": "Protection II: 2.5s",
    "stardewcraft.weapon.skill.dwarf_rune_guard.effect.2": "Energy: +6 on hit, +3 on miss",
    "stardewcraft.weapon.skill.dwarf_rune_guard.effect.3": "Slow: 2s",

    "stardewcraft.weapon.skill.elf_blade_leaf": "Moonleaf Firefly Blade",
    "stardewcraft.weapon.skill.elf_blade_leaf.desc.1": "Effect: Summon 3 firefly leaves orbiting for 5s",
    "stardewcraft.weapon.skill.elf_blade_leaf.desc.2": "Hit: Leaves fly toward target",
    "stardewcraft.weapon.skill.elf_blade_leaf.effect.1": "Per leaf damage: 50%",
    "stardewcraft.weapon.skill.elf_blade_leaf.effect.2": "Mark: Crit rate +5%/stack",
    "stardewcraft.weapon.skill.elf_blade_leaf.effect.3": "Cooldown: 7s after end",

    "stardewcraft.weapon.skill.eternal_collapse": "Eternal Collapse",
    "stardewcraft.weapon.skill.eternal_collapse.desc.1": "Effect: Summon a black hole domain for 3.5s with pull",
    "stardewcraft.weapon.skill.eternal_collapse.desc.2": "Multi-hit slashes; Singularity increases hit count",
    "stardewcraft.weapon.skill.eternal_collapse.desc.3": "Singularity \u226516: Bonus collapse finisher",
    "stardewcraft.weapon.skill.eternal_collapse.effect.1": "Damage: 80%/hit (base 6 hits)",
    "stardewcraft.weapon.skill.eternal_collapse.effect.2": "Bonus: +1 hit per 5 stacks, crit rate +5%",
    "stardewcraft.weapon.skill.eternal_collapse.effect.3": "Finisher: 300% damage",

    "stardewcraft.weapon.skill.femur_slam": "Femur Slam",
    "stardewcraft.weapon.skill.femur_slam.desc.2": "Hit: Sluggish 2s; single target extra stagger",
    "stardewcraft.weapon.skill.femur_slam.effect.1": "Damage: 120%",
    "stardewcraft.weapon.skill.femur_slam.effect.2": "Sluggish: Move speed -20% (2s)",
    "stardewcraft.weapon.skill.femur_slam.effect.3": "Single target: Increased knockback + 0.2s stagger",

    "stardewcraft.weapon.skill.fishcatch_thrust": "Fish Catch Thrust",
    "stardewcraft.weapon.skill.fishcatch_thrust.desc.1": "Effect: Triple thrust at nearest target within 2.5 blocks",
    "stardewcraft.weapon.skill.fishcatch_thrust.desc.2": "Hit: If inventory has fish, gain Fish Catch",
    "stardewcraft.weapon.skill.fishcatch_thrust.effect.1": "Multi-stab: 40% x3",
    "stardewcraft.weapon.skill.fishcatch_thrust.effect.2": "Fish Catch: Skill damage +10% (5s)",
    "stardewcraft.weapon.skill.fishcatch_thrust.effect.3": "Slow: Move speed -10% (5s)",

    "stardewcraft.weapon.skill.forest_blessing": "Forest Blessing",
    "stardewcraft.weapon.skill.forest_blessing.desc.1": "Effect: Gain blessing on hit",
    "stardewcraft.weapon.skill.forest_blessing.desc.2": "Blessing: Continuously restores HP",
    "stardewcraft.weapon.skill.forest_blessing.effect.1": "Hit: +2 HP every 0.5s (4s)",
    "stardewcraft.weapon.skill.forest_blessing.effect.2": "Miss: +1 HP every 0.5s (4s)",

    "stardewcraft.weapon.skill.galaxy_dagger_starleap": "Star Leap Backstab",
    "stardewcraft.weapon.skill.galaxy_dagger_starleap.desc.1": "Effect: Leap behind and slash, 140% damage",
    "stardewcraft.weapon.skill.galaxy_dagger_starleap.desc.2": "If target has Star Mark: +30% bonus damage",
    "stardewcraft.weapon.skill.galaxy_dagger_starleap.effect.1": "Consumes Star Mark to enhance",
    "stardewcraft.weapon.skill.galaxy_dagger_starleap.effect.2": "Target no AI for 0.8s",
    "stardewcraft.weapon.skill.galaxy_dagger_starleap.effect.3": "Energy: 10",

    "stardewcraft.weapon.skill.galaxy_dagger_starstab": "Star Trail Pierce",
    "stardewcraft.weapon.skill.galaxy_dagger_starstab.desc.1": "Effect: 3-hit combo, each hit 50% damage",
    "stardewcraft.weapon.skill.galaxy_dagger_starstab.desc.2": "Applies Star Mark for 3s",
    "stardewcraft.weapon.skill.galaxy_dagger_starstab.effect.1": "Marked target: Next hit deals 80% bonus damage",
    "stardewcraft.weapon.skill.galaxy_dagger_starstab.effect.2": "Bonus hit clears the mark",

    "stardewcraft.weapon.skill.galaxy_judgement": "Galaxy Judgement",
    "stardewcraft.weapon.skill.galaxy_judgement.desc.1": "Effect: Unleash a galactic heavy slash and summon starfall",
    "stardewcraft.weapon.skill.galaxy_judgement.desc.2": "Each 4 Star Trail stacks grants +1 starfall",
    "stardewcraft.weapon.skill.galaxy_judgement.desc.3": "12 Star Trail stacks: Main slash guaranteed crit",
    "stardewcraft.weapon.skill.galaxy_judgement.effect.1": "Cost: All Star Trail stacks",
    "stardewcraft.weapon.skill.galaxy_judgement.effect.2": "Damage: Main slash 220% + Starfall 70%/hit",
    "stardewcraft.weapon.skill.galaxy_judgement.effect.3": "Cap: Max +3 extra starfalls",

    "stardewcraft.weapon.skill.holy_domain": "Dawn Sanctuary",
    "stardewcraft.weapon.skill.holy_domain.desc.1": "Effect: Deploy sanctuary for 4s with periodic pulses",
    "stardewcraft.weapon.skill.holy_domain.desc.2": "Pulses deal damage and expand outward",
    "stardewcraft.weapon.skill.holy_domain.effect.1": "Energy: 10",
    "stardewcraft.weapon.skill.holy_domain.effect.2": "Heal: +4 per pulse",

    "stardewcraft.weapon.skill.holy_smite": "Holy Smite",
    "stardewcraft.weapon.skill.holy_smite.desc.1": "Effect: Holy light slash heals on hit",
    "stardewcraft.weapon.skill.holy_smite.desc.2": "Gain Radiant Dodge",
    "stardewcraft.weapon.skill.holy_smite.effect.1": "Heal: 6",
    "stardewcraft.weapon.skill.holy_smite.effect.2": "Dodge: +20% (2s)",

    "stardewcraft.weapon.skill.infinity_dagger_singularity_backstab.desc.1": "Effect: Backstab twice, each hit 70% damage",
    "stardewcraft.weapon.skill.infinity_dagger_singularity_backstab.desc.2": "If target has Singularity Mark: 2nd hit +20% bonus damage",
    "stardewcraft.weapon.skill.infinity_dagger_singularity_backstab.effect.1": "Consumes Singularity Mark for bonus damage",
    "stardewcraft.weapon.skill.infinity_dagger_singularity_backstab.effect.2": "Target no AI for 1.2s",
    "stardewcraft.weapon.skill.infinity_dagger_singularity_backstab.effect.3": "Energy: 12",

    "stardewcraft.weapon.skill.infinity_dagger_singularity_stab": "Singularity Pierce",
    "stardewcraft.weapon.skill.infinity_dagger_singularity_stab.desc.1": "Effect: 4-hit combo, each hit 22% damage",
    "stardewcraft.weapon.skill.infinity_dagger_singularity_stab.desc.2": "Applies Singularity Mark for 3s",
    "stardewcraft.weapon.skill.infinity_dagger_singularity_stab.effect.1": "Marked target: Next hit deals 120% bonus damage",
    "stardewcraft.weapon.skill.infinity_dagger_singularity_stab.effect.2": "Bonus hit clears the mark",

    "stardewcraft.weapon.skill.insect_dash": "Wing Dash",
    "stardewcraft.weapon.skill.insect_dash.desc.2": "Hit 2 targets to refresh, max 3 times",
    "stardewcraft.weapon.skill.insect_dash.effect.1": "Damage: 80% \u2192 100% \u2192 120%",
    "stardewcraft.weapon.skill.insect_dash.effect.2": "Energy: 3 / 5 / 7",
    "stardewcraft.weapon.skill.insect_dash.effect.3": "After 3rd dash: Speed I 3s",

    "stardewcraft.weapon.skill.insect_eye_stance": "Compound Eye Stance",
    "stardewcraft.weapon.skill.insect_eye_stance.desc.1": "Effect: Enter stance, next hit guaranteed crit",
    "stardewcraft.weapon.skill.insect_eye_stance.desc.2": "Hit: 105% damage and applies Vulnerability II",
    "stardewcraft.weapon.skill.insect_eye_stance.effect.1": "Duration: 1.5s",
    "stardewcraft.weapon.skill.insect_eye_stance.effect.2": "Vulnerability II: 3s",

    "stardewcraft.weapon.skill.iridium_needle_frenzy": "Iridium Frenzy",
    "stardewcraft.weapon.skill.iridium_needle_frenzy.desc.1": "Effect: Enter Iridium Frenzy for 6s",
    "stardewcraft.weapon.skill.iridium_needle_frenzy.desc.2": "Crit: Restore HP/energy and apply Vulnerability II",
    "stardewcraft.weapon.skill.iridium_needle_frenzy.effect.1": "Energy: 10",
    "stardewcraft.weapon.skill.iridium_needle_frenzy.effect.2": "Crit rate +30%",
    "stardewcraft.weapon.skill.iridium_needle_frenzy.effect.3": "Crit: Restore 5 HP + 10 energy",
    "stardewcraft.weapon.skill.iridium_needle_frenzy.effect.4": "Crit: Vulnerability II 2s",
    "stardewcraft.weapon.skill.iridium_needle_frenzy.effect.5": "Speed: 6s",

    "stardewcraft.weapon.skill.iridium_needle_thrust": "Triple Needle Slash",
    "stardewcraft.weapon.skill.iridium_needle_thrust.desc.1": "Effect: Rapid 3-hit forward slash",
    "stardewcraft.weapon.skill.iridium_needle_thrust.desc.2": "Passive: Every 3rd hit is a guaranteed crit",
    "stardewcraft.weapon.skill.iridium_needle_thrust.effect.1": "Damage: 40% x3",
    "stardewcraft.weapon.skill.iridium_needle_thrust.effect.2": "3rd hit: Guaranteed crit",

    "stardewcraft.weapon.skill.iron_dirk_thrust": "Shadow Thrust",
    "stardewcraft.weapon.skill.iron_dirk_thrust.desc.1": "Effect: Thrust at nearest target within 7 blocks",
    "stardewcraft.weapon.skill.iron_dirk_thrust.desc.2": "Teleport: First to front, then behind target 3 blocks",
    "stardewcraft.weapon.skill.iron_dirk_thrust.effect.1": "Damage: 150%",
    "stardewcraft.weapon.skill.iron_dirk_thrust.effect.2": "Crit: +10% this strike",
    "stardewcraft.weapon.skill.iron_dirk_thrust.effect.3": "Invulnerable: During thrust",

    "stardewcraft.weapon.skill.lava_katana_brand": "Molten Brand",
    "stardewcraft.weapon.skill.lava_katana_brand.desc.1": "Effect: Hit applies Molten Brand and burn",
    "stardewcraft.weapon.skill.lava_katana_brand.desc.2": "Hits during Brand stack Heat",
    "stardewcraft.weapon.skill.lava_katana_brand.effect.1": "Molten Brand: Lasts 6s",
    "stardewcraft.weapon.skill.lava_katana_brand.effect.2": "Burn: 15% / 0.5s",
    "stardewcraft.weapon.skill.lava_katana_brand.effect.3": "Heat: +4% per stack (max 5)",

    "stardewcraft.weapon.skill.lava_katana_reverb": "Molten Reverb",
    "stardewcraft.weapon.skill.lava_katana_reverb.desc.1": "Effect: If no branded target, applies Brand first",
    "stardewcraft.weapon.skill.lava_katana_reverb.desc.2": "Reverb settles Brand damage after 4s",
    "stardewcraft.weapon.skill.lava_katana_reverb.effect.1": "Energy: 12",
    "stardewcraft.weapon.skill.lava_katana_reverb.effect.2": "Reverb: Heat +8% with no cap",
    "stardewcraft.weapon.skill.lava_katana_reverb.effect.3": "Finisher: Remaining burn ticks \u00d7 (150% + 5%/Heat)",

    "stardewcraft.weapon.skill.light_counter": "Light Counter",
    "stardewcraft.weapon.skill.light_counter.desc.1": "Effect: Enter parry window",
    "stardewcraft.weapon.skill.light_counter.desc.2": "On hit taken: Trigger counter and reduce damage",
    "stardewcraft.weapon.skill.light_counter.effect.1": "Damage Reduction: 40% taken; Counter: 120%",

    "stardewcraft.weapon.skill.meowmere_shot": "Rainbow Shot",
    "stardewcraft.weapon.skill.meowmere_shot.desc.1": "Effect: Fire a cat projectile in a straight line",
    "stardewcraft.weapon.skill.meowmere_shot.desc.2": "Trait: Bounces on collision",
    "stardewcraft.weapon.skill.meowmere_shot.effect.1": "Bounces: 2",
    "stardewcraft.weapon.skill.meowmere_shot.effect.2": "Pierce: None",

    "stardewcraft.weapon.skill.meowmere_symphony": "Cat Symphony",
    "stardewcraft.weapon.skill.meowmere_symphony.desc.1": "Effect: Consume energy, fire 5 cats in a cone",
    "stardewcraft.weapon.skill.meowmere_symphony.desc.2": "Each cat hits independently",
    "stardewcraft.weapon.skill.meowmere_symphony.effect.1": "Energy: 10",
    "stardewcraft.weapon.skill.meowmere_symphony.effect.2": "Pierce: 1 enemy",

    "stardewcraft.weapon.skill.obsidian_crack": "Obsidian Crack",
    "stardewcraft.weapon.skill.obsidian_crack.desc.1": "Effect: Cleave a 6-block crack line forward",
    "stardewcraft.weapon.skill.obsidian_crack.desc.2": "Crack detonates, pulls and slashes",
    "stardewcraft.weapon.skill.obsidian_crack.effect.1": "Energy: 10",
    "stardewcraft.weapon.skill.obsidian_crack.effect.2": "Pull: 3 block radius",
    "stardewcraft.weapon.skill.obsidian_crack.effect.3": "Sluggish: 2s",

    "stardewcraft.weapon.skill.obsidian_resonance": "Obsidian Resonance",
    "stardewcraft.weapon.skill.obsidian_resonance.desc.1": "[Passive] Auto-charges every 7s",
    "stardewcraft.weapon.skill.obsidian_resonance.desc.2": "Charged: Next normal attack deals bonus damage (guaranteed crit if first hit crits)",
    "stardewcraft.weapon.skill.obsidian_resonance.effect.1": "Charge: 7s",
    "stardewcraft.weapon.skill.obsidian_resonance.effect.2": "Bonus: 70% damage",

    "stardewcraft.weapon.skill.ossified_execution": "Ossified Execution",
    "stardewcraft.weapon.skill.ossified_execution.desc.1": "Effect: Create execution circle below a Bone-marked target",
    "stardewcraft.weapon.skill.ossified_execution.desc.2": "Lasts 3s, deals damage per second",
    "stardewcraft.weapon.skill.ossified_execution.effect.1": "Energy: 10",
    "stardewcraft.weapon.skill.ossified_execution.effect.2": "Buff: +20% crit damage in area, slow pull",

    "stardewcraft.weapon.skill.ossified_mark": "Bone Mark",
    "stardewcraft.weapon.skill.ossified_mark.desc.1": "Effect: Apply Bone Mark to target (3s)",
    "stardewcraft.weapon.skill.ossified_mark.desc.2": "Bone Mark: Crit rate +10%, first crit triggers bonus",
    "stardewcraft.weapon.skill.ossified_mark.effect.1": "Cooldown: 6s (no crit \u2192 4s)",
    "stardewcraft.weapon.skill.ossified_mark.effect.2": "Bonus: 100% damage",

    "stardewcraft.weapon.skill.shadow_dagger_execute": "Shadow Execute",
    "stardewcraft.weapon.skill.shadow_dagger_execute.desc.1": "Effect: Shadow strike a single target in front",
    "stardewcraft.weapon.skill.shadow_dagger_execute.desc.2": "Execute: Triggers on low-HP targets",
    "stardewcraft.weapon.skill.shadow_dagger_execute.effect.1": "Execute threshold: Target HP \u226430%",
    "stardewcraft.weapon.skill.shadow_dagger_execute.effect.2": "Execute: +100% bonus damage",
    "stardewcraft.weapon.skill.shadow_dagger_execute.effect.3": "No execute: Refund 50% cooldown",

    "stardewcraft.weapon.skill.silver_foldback": "Silver Foldback",
    "stardewcraft.weapon.skill.silver_foldback.desc.1": "Effect: Dash to nearest enemy within 5 blocks and slash",
    "stardewcraft.weapon.skill.silver_foldback.desc.2": "Foldback: Right-click to return slash and teleport back",
    "stardewcraft.weapon.skill.silver_foldback.effect.1": "Foldback: Lasts 1s; left-click return slash without teleport",
    "stardewcraft.weapon.skill.silver_foldback.effect.2": "No target: Dash 5 blocks (no foldback)",

    "stardewcraft.weapon.skill.singularity_evolve": "Singularity Evolution",
    "stardewcraft.weapon.skill.singularity_evolve.desc.1": "Effect: Pull enemies within 4 blocks and detonate",
    "stardewcraft.weapon.skill.singularity_evolve.desc.2": "Then dash 5 blocks and slash",
    "stardewcraft.weapon.skill.singularity_evolve.desc.3": "Evolved: Dash leaves a rift trail",
    "stardewcraft.weapon.skill.singularity_evolve.effect.1": "Hit: +4 Singularity +10 energy +5 HP",
    "stardewcraft.weapon.skill.singularity_evolve.effect.2": "Rift: Lasts 2s, stepping in deals extra damage",
    "stardewcraft.weapon.skill.singularity_evolve.effect.3": "Evolved: Enhanced effects",

    "stardewcraft.weapon.skill.startrail_rift": "Star Trail Rift",
    "stardewcraft.weapon.skill.startrail_rift.desc.1": "Effect: Dash forward 4.5 blocks and slash",
    "stardewcraft.weapon.skill.startrail_rift.desc.2": "Hit: Refund Star Trail, energy and HP",
    "stardewcraft.weapon.skill.startrail_rift.effect.1": "Star Trail \u22656: +20% crit rate this strike",
    "stardewcraft.weapon.skill.startrail_rift.effect.2": "Hit: +2 Star Trail +6 energy +3 HP",
    "stardewcraft.weapon.skill.startrail_rift.effect.3": "After cast: Speed I 7s",

    "stardewcraft.weapon.skill.steel_falchion_line.desc.1": "Effect: Etch a 7-block line below nearest enemy",
    "stardewcraft.weapon.skill.steel_falchion_line.desc.2": "First enemy to step on it takes sustained damage",
    "stardewcraft.weapon.skill.steel_falchion_line.effect.1": "Line: Lasts 5s",
    "stardewcraft.weapon.skill.steel_falchion_line.effect.2": "Self crossing: Speed II 5s",

    "stardewcraft.weapon.skill.steel_falchion_trace": "Slash Trace Echo",
    "stardewcraft.weapon.skill.steel_falchion_trace.desc.1": "Effect: Enter 5s Slash Trace state; movement etches lines",
    "stardewcraft.weapon.skill.steel_falchion_trace.desc.2": "On end: Lines detonate, damaging within 1 block",
    "stardewcraft.weapon.skill.steel_falchion_trace.effect.1": "Energy: 12",
    "stardewcraft.weapon.skill.steel_falchion_trace.effect.2": "Line: 50%/s (5s)",
    "stardewcraft.weapon.skill.steel_falchion_trace.effect.3": "During trace: Speed III",

    "stardewcraft.weapon.skill.steel_spine_fury": "Steel Spine Fury",
    "stardewcraft.weapon.skill.steel_spine_fury.desc.1": "Effect: Enter Steel Spine stance awaiting counter-shock",
    "stardewcraft.weapon.skill.steel_spine_fury.desc.2": "Next hit unleashes charged burst",
    "stardewcraft.weapon.skill.steel_spine_fury.effect.1": "Hit taken: Bonus damage (max 12)",
    "stardewcraft.weapon.skill.steel_spine_fury.effect.2": "No hit taken: Next hit +40% damage",

    "stardewcraft.weapon.skill.tempered_billet.desc.1": "Effect: Launch 3 billets that auto-track enemies",
    "stardewcraft.weapon.skill.tempered_billet.desc.2": "On hit: Creates fire ring sweep",
    "stardewcraft.weapon.skill.tempered_billet.effect.1": "Energy: 10",
    "stardewcraft.weapon.skill.tempered_billet.effect.2": "Fire ring: 60% (2.5 block radius)",

    "stardewcraft.weapon.skill.tempered_quench": "Tempered Quench",
    "stardewcraft.weapon.skill.tempered_quench.desc.1": "Effect: Hot forge slash on hit",
    "stardewcraft.weapon.skill.tempered_quench.desc.2": "After 1s: Triggers quench detonation",
    "stardewcraft.weapon.skill.tempered_quench.effect.1": "Detonation: 45% damage",
    "stardewcraft.weapon.skill.tempered_quench.effect.2": "Vulnerability II: 3s",

    "stardewcraft.weapon.skill.templar_judgement": "Templar Judgement",
    "stardewcraft.weapon.skill.templar_judgement.desc.1": "Effect: Mark nearby enemies as judgement targets",
    "stardewcraft.weapon.skill.templar_judgement.desc.2": "Redirects 35% of damage taken and settles with slash",
    "stardewcraft.weapon.skill.templar_judgement.effect.1": "Energy: 10",
    "stardewcraft.weapon.skill.templar_judgement.effect.2": "Duration: 5s",

    "stardewcraft.weapon.skill.templar_vow": "Templar Vow",
    "stardewcraft.weapon.skill.templar_vow.desc.1": "Effect: Enter Vow stance",
    "stardewcraft.weapon.skill.templar_vow.desc.2": "Hit taken: Counter slash; No hit: Light slash",
    "stardewcraft.weapon.skill.templar_vow.effect.1": "Duration: 2s",
    "stardewcraft.weapon.skill.templar_vow.effect.2": "Cooldown: Starts after stance ends",

    "stardewcraft.weapon.skill.tetanus_strike": "Tetanus Strike",
    "stardewcraft.weapon.skill.tetanus_strike.desc.1": "Effect: Strike and apply Tetanus",
    "stardewcraft.weapon.skill.tetanus_strike.desc.2": "Hit: Target vulnerable for 3s",
    "stardewcraft.weapon.skill.tetanus_strike.effect.1": "Vulnerability: +10% (3s)",

    "stardewcraft.weapon.skill.tide_anchor": "Tide Anchor",
    "stardewcraft.weapon.skill.tide_anchor.desc.1": "Effect: Throw a Tide Anchor, water ring AoE on landing",
    "stardewcraft.weapon.skill.tide_anchor.desc.2": "Marked target: Teleported to anchor and immobilized",
    "stardewcraft.weapon.skill.tide_anchor.effect.1": "Energy: 10",
    "stardewcraft.weapon.skill.tide_anchor.effect.2": "Immobilize: 5s",

    "stardewcraft.weapon.skill.tide_mark": "Tide Mark",
    "stardewcraft.weapon.skill.tide_mark.desc.1": "Effect: Apply Tide Mark",
    "stardewcraft.weapon.skill.tide_mark.desc.2": "Mark: Your damage to target deals bonus damage",
    "stardewcraft.weapon.skill.tide_mark.effect.1": "Duration: 5s",
    "stardewcraft.weapon.skill.tide_mark.effect.2": "Bonus: +30% (displayed separately)",

    "stardewcraft.weapon.skill.tide_reel": "Tide Reel",
    "stardewcraft.weapon.skill.tide_reel.desc.1": "Effect: Heavy thrust reel, pulling target closer",
    "stardewcraft.weapon.skill.tide_reel.desc.2": "Fish Catch: +60% bonus, consumes Fish Catch",
    "stardewcraft.weapon.skill.tide_reel.effect.1": "Energy: 10",
    "stardewcraft.weapon.skill.tide_reel.effect.2": "Fish in inventory: Cooldown -2s",
    "stardewcraft.weapon.skill.tide_reel.effect.3": "Pull: Short-range pull",

    "stardewcraft.weapon.skill.tree_blessing": "Tree Blessing",
    "stardewcraft.weapon.skill.tree_blessing.desc.1": "Effect: Gain protection on hit",
    "stardewcraft.weapon.skill.tree_blessing.desc.2": "Protection: Briefly reduces damage taken",

    "stardewcraft.weapon.skill.wicked_kris_nest_burst": "Serpent Nest Burst",
    "stardewcraft.weapon.skill.wicked_kris_nest_burst.desc.1": "Effect: Thrust single target and inject venom",
    "stardewcraft.weapon.skill.wicked_kris_nest_burst.desc.2": "After 3s: Detonates remaining venom, AoE nearby",
    "stardewcraft.weapon.skill.wicked_kris_nest_burst.effect.1": "Venom: 5 stacks, lasts 10s",
    "stardewcraft.weapon.skill.wicked_kris_nest_burst.effect.2": "Detonation: Remaining venom \u00d71.5",
    "stardewcraft.weapon.skill.wicked_kris_nest_burst.effect.3": "Energy: 10",

    "stardewcraft.weapon.skill.wicked_kris_venom_ripple": "Venom Ripple",
    "stardewcraft.weapon.skill.wicked_kris_venom_ripple.desc.1": "Effect: Release ring of poison mist, damages nearby enemies",
    "stardewcraft.weapon.skill.wicked_kris_venom_ripple.desc.2": "Hit: Apply 5 venom stacks and gain Sprint I",
    "stardewcraft.weapon.skill.wicked_kris_venom_ripple.effect.1": "Venom: 10%/s per stack",
    "stardewcraft.weapon.skill.wicked_kris_venom_ripple.effect.2": "Duration: 5s (5 stacks)",
    "stardewcraft.weapon.skill.wicked_kris_venom_ripple.effect.3": "Sprint I: 2s",

    "stardewcraft.weapon.skill.wind_spire_thrust": "Wind Spire Thrust",
    "stardewcraft.weapon.skill.wind_spire_thrust.desc.1": "Effect: Thrust at nearest target within 6 blocks",
    "stardewcraft.weapon.skill.wind_spire_thrust.desc.2": "Hit: Enter Gale Phase for 3s",
    "stardewcraft.weapon.skill.wind_spire_thrust.effect.1": "Damage: 150%",
    "stardewcraft.weapon.skill.wind_spire_thrust.effect.2": "Crit: Gale normal attack +10%",
    "stardewcraft.weapon.skill.wind_spire_thrust.effect.3": "No target: Dash forward 4 blocks",

    "stardewcraft.weapon.skill.yeti_tooth_mark": "Frost Fang Mark",
    "stardewcraft.weapon.skill.yeti_tooth_mark.desc.1": "Effect: Hit applies Frost Fang Mark",
    "stardewcraft.weapon.skill.yeti_tooth_mark.desc.2": "During mark: Next hit freezes",
    "stardewcraft.weapon.skill.yeti_tooth_mark.effect.1": "Slow: 20% (3s)",
    "stardewcraft.weapon.skill.yeti_tooth_mark.effect.2": "Freeze: 2s (once)",

    "stardewcraft.weapon.skill.yeti_tooth_spine": "Frost Spine Shatter",
    "stardewcraft.weapon.skill.yeti_tooth_spine.desc.1": "Effect: Fire 5 frost spines in a 120\u00b0 forward arc",
    "stardewcraft.weapon.skill.yeti_tooth_spine.desc.2": "Hit: Slow; already slowed targets freeze for 3s",
    "stardewcraft.weapon.skill.yeti_tooth_spine.effect.1": "Energy: 10",
    "stardewcraft.weapon.skill.yeti_tooth_spine.effect.2": "Range: 6 blocks",

    # ── subtitles ──
    "subtitles.stardewcraft.cancel": "Cancel",
    "subtitles.stardewcraft.tree_crack": "Tree cracking",
    "subtitles.stardewcraft.tree_thud": "Tree thud",

    # ── ui ──
    "ui.stardewcraft.skillhud.level": "Level: %d",
    "ui.stardewcraft.skillhud.levelup": "%s Level Up!",
}

def smart_title(s):
    """Title case with lowercase articles/prepositions."""
    words = s.split()
    small = {'a','an','the','of','in','on','at','to','for','and','but','or','nor','is'}
    result = []
    for i, w in enumerate(words):
        if i == 0 or w.lower() not in small:
            result.append(w.capitalize())
        else:
            result.append(w.lower())
    return ' '.join(result)

def translate_key(key, zh_val):
    # 1. Check manual dict
    if key in M:
        return M[key]

    # 2. Programmatic categories: item / block / entity / effect / container
    for prefix in ['item.stardewcraft.', 'block.stardewcraft.', 'entity.stardewcraft.',
                   'effect.stardewcraft.', 'container.stardewcraft.']:
        if key.startswith(prefix):
            suffix = key[len(prefix):]
            if suffix in NAME_FIX:
                return NAME_FIX[suffix]
            return smart_title(suffix.replace('_', ' '))

    # 3. Weapon skill names (no desc/effect suffix) -> title case from key
    if key.startswith('stardewcraft.weapon.skill.'):
        rest = key[len('stardewcraft.weapon.skill.'):]
        # If it has .desc. or .effect. sub-keys, fall through to fallback
        if '.desc.' not in rest and '.effect.' not in rest:
            return smart_title(rest.replace('_', ' '))

    # 4. Fallback: title case from last key segment
    parts = key.rsplit('.', 1)
    return smart_title(parts[-1].replace('_', ' '))

# Generate translations
new_entries = {}
fallback_keys = []
for key in missing:
    val = translate_key(key, zh[key])
    new_entries[key] = val
    if key not in M and not any(key.startswith(p) for p in
        ['item.stardewcraft.', 'block.stardewcraft.', 'entity.stardewcraft.',
         'effect.stardewcraft.', 'container.stardewcraft.']):
        fallback_keys.append(key)

# Merge and sort
en.update(new_entries)
sorted_en = dict(sorted(en.items()))

with open('src/main/resources/assets/stardewcraft/lang/en_us.json', 'w') as f:
    json.dump(sorted_en, f, indent=2, ensure_ascii=False)

print(f"Added {len(new_entries)} entries. Total en_us keys: {len(sorted_en)}")
if fallback_keys:
    print(f"\n{len(fallback_keys)} keys used fallback (title case from key):")
    for k in fallback_keys:
        print(f"  {k} -> {new_entries[k]}")
