# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.sheep_baby.root] run return 0
execute if entity @s[tag=aj.sheep_baby.animation.idle.playing] run function animated_java:sheep_baby/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.sheep_baby.animation.walk.playing] run function animated_java:sheep_baby/animations/walk/zzz/on_tick
execute on passengers run rotate @s ~ ~