# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:george rig_hash set value '42168d25d993dcec2000c40f0f6bfabfec4032c3e5bdd3a33647a46108b3f4ca'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy