# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '3a75543257fde44058e6703d712ecb0ca551e7f3f4bf246f19ca6be675e69b05'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack