# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.goat_baby.node.ear_left] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_ear_left set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.goat_baby.node.ear_right] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_ear_right set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.goat_baby.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.goat_baby.node.bone] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.goat_baby.node.tail] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_tail set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.goat_baby.node.body] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_body set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.goat_baby.node.leg_left] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leg_left set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.goat_baby.node.leg_right] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leg_right set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.goat_baby.node.leg2_left] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leg2_left set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.goat_baby.node.leg2_right] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leg2_right set from storage animated_java:gu out