# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'eb63d22972e47575cc752e2420f0a111c7f3f2c6e0b3fe61b2aba224b77e9b8a'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack