# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_ear_left) {transformation: [-1f,0f,0f,0.0485f,0f,1f,0f,0.2042f,0f,0f,-1f,0.0668f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ear_right) {transformation: [-1f,0f,0f,-0.0485f,0f,1f,0f,0.2042f,0f,0f,-1f,0.0668f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1256f,0f,0f,-1f,0.0375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.0542f,0f,0f,-1f,-0.087f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}