# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '6da77a4dd954c8483c77a9227ea1ef4554b37d053a071cc97e255f8b67dd98bd'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack