# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '74876a3d96fd5c3f7669b040c92106ac5fe69058dc1f6c28141745d628172882'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack