# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '970e93c08fd33420a076dd8e00e39348edba725c52695fe715fe757264e7d427'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack