# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:leah rig_hash set value 'f81bceb16d788b404380afffd7b253b5f3d8691c1535b87276252abb67b2b894'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy