# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:gus rig_hash set value '410178876728da2fb7d005fd26f40a22ab682d4b6d6664669440a225b4daf559'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy