# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '77e21582ffe936a8fda55f89e6d9e3ace2b2c5d104cade26e7ab93b161900f1f'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack