# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:evelyn rig_hash set value '9338617fa1f32bcd6e04306bb663982b34929cde50e14d23c8eadea34b932912'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy