# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:goat_baby rig_hash set value '970e93c08fd33420a076dd8e00e39348edba725c52695fe715fe757264e7d427'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy