# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_ear_left) {transformation: [-1f,0f,0f,0.0789f,0f,0.9909f,0.1349f,0.454f,0f,0.1349f,-0.9909f,0.252f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ear_right) {transformation: [-1f,0f,0f,-0.0788f,0f,0.9909f,0.1349f,0.454f,0f,0.1349f,-0.9909f,0.252f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9909f,0.1349f,0.3443f,0f,0.1349f,-0.9909f,0.2338f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.0985f,0f,0f,-1f,-0.0619f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3255f,0f,0f,-1f,-0.2054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.211f,0f,0f,-1f,0.0125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_left) {transformation: [-1f,0f,0f,0.1125f,0f,1f,0f,0.1469f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_right) {transformation: [-1f,0f,0f,-0.1125f,0f,1f,0f,0.1469f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_left) {transformation: [-1f,0f,0f,0.1125f,0f,1f,0f,0.1469f,0f,0f,-1f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_right) {transformation: [-1f,0f,0f,-0.1125f,0f,1f,0f,0.1469f,0f,0f,-1f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}