# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '7154ca3cc1193269815184169d84260e8d87c8b8dfbe2ba9d4ae11cb94c802a0'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack