# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'dc6f259ae049d999d53c2cfc4203f833de1b544999a2b1dc153ac468de162587'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack