# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '00147baf9f88e98b232ea95c1feb68104a62ce4ccc4ac8e742613bc6233fa163'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack