# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '2320680f51c38c44b0a17d15e8b4c95615940dfb522fab6e586dfc8e4a16549a'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack