# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:willy rig_hash set value '6da77a4dd954c8483c77a9227ea1ef4554b37d053a071cc97e255f8b67dd98bd'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy