# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '817427d487ad8b8c9c6b5611fc9a5eeef27c33c7eaec64a633c84bc68727d3db'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack