# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '433ffeac74b33e60a4032c33bdff8b39a8be802a7354c359131272ba0765704e'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack