# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '9338617fa1f32bcd6e04306bb663982b34929cde50e14d23c8eadea34b932912'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack